In [3]:
# dictionary 생성
d = {"name" : "김태경"}
print(d)
print(type(d))
print(d["name"])

{'name': '김태경'}
<class 'dict'>
김태경

In [4]:
# python 객체를 json 문자열로 변환
import json

# json.dumps()함수는 아스키 문자 외의 다른 문자를 16진수로 출력하기 때문에 한글이 제대로 보이지 않음
d_str = json.dumps(d)
print(d_str)

# json.dumps()함수에서 한글을 보기 위해서 ensure_ascii 매개변수를 False로 설정
d_str = json.dumps(d, ensure_ascii=False)
print(d_str)
print(type(d_str))

{"name": "\uae40\ud0dc\uacbd"}
{"name": "김태경"}
<class 'str'>

In [5]:
# json 문자열을 python 객체로 변환
d2 = json.loads(d_str)

print(d2)
print(type(d2))

{'name': '김태경'}
<class 'dict'>

In [6]:
# 여러 항목을 가진 json 문자열을 python 객체로 변환
d3 = json.loads('{"name" : "김태경", "job" : ["개발자", "댄서"], "age" : 20}')

print(d3)
print(d3["name"])
print(type(d3["job"]))
print(d3["job"][1])
print(d3["age"])
print(type(d3))

{'name': '김태경', 'job': ['개발자', '댄서'], 'age': 20}
김태경
<class 'list'>
댄서
20
<class 'dict'>

In [7]:
d4_str = """
[
    {"name" : "김태경1", "job" : "개발자", "age" : 20},
    {"name" : "김태경2", "job" : "댄서", "age" : 21}
]
"""

d4 = json.loads(d4_str)
print(d4[0]["name"])

김태경1

In [8]:
# json 문자열을 데이터프레임으로 변환하는 방법 1 - 문자열을 바로 데이터프레임으로 변환
from io import StringIO
import pandas as pd

pd.read_json(StringIO(d4_str))

   name  job  age
0  김태경1  개발자   20
1  김태경2   댄서   21

In [9]:
# json 문자열을 데이터프레임으로 변환하는 방법 2 - 문자열을 python 객체로 변환 후 데이터프레임으로 변환
pd.DataFrame(d4)

   name  job  age
0  김태경1  개발자   20
1  김태경2   댄서   21

In [10]:
# XML문자열을 python 객체로 변환

import xml.etree.ElementTree as et

# json pkg는 json 문자열을 python 객체로 변환
# fromstring() 함수가 반환하는 객체는 단순 python 객체가 아닌 ElementTree 모듈 아래에 정의된 Element 클래스의 객체

x_str = """
<info>
    <name>김태경</name>
    <job>개발자</job>
    <age>20</age>
</info>
"""

my_info = et.fromstring(x_str)

print(my_info)
print(type(my_info))

<Element 'info' at 0x0000023D88DF2C00>
<class 'xml.etree.ElementTree.Element'>

In [11]:
# my_info 객체는 x_str에서 가장 먼저 등장하는 부모 element인 info에 해당
# my_info 객체의 tag 속성을 출력하면 element 이름 확인 가능
print(my_info.tag)

info

In [12]:
# 자식 element 확인 방법

# 1. my_info element의 자식 element 구하기
info_childs = list(my_info)
print(info_childs)
print()

# 2. 각각의 자식 element에 담긴 text를 읽어오기
name, job, age = info_childs
print(name.text)
print(job.text)
print(age.text)

[<Element 'name' at 0x0000023D88DF2C50>, <Element 'job' at 0x0000023D88DF2CF0>, <Element 'age' at 0x0000023D88DF2D90>]

김태경
개발자
20

In [13]:
# 자식 element가 일정하다는 보장이 없기 때문에 위와 같이 순서대로 자식 element를 찾는 것은 위험함
# findtext() method에서 찾으려는 tag를 넣어주면 해당 element를 찾아서 text로 변환
name = my_info.findtext("name")
job = my_info.findtext("job")
age = my_info.findtext("age")

print(name)
print(job)
print(age)

김태경
개발자
20

In [14]:
# 여러 자식 element 확인
x2_str = """
<people>
    <person>
        <name>김태경1</name>
        <job>개발자</job>
        <age>20</age>
    </person>
    <person>
        <name>김태경2</name>
        <job>댄서</job>
        <age>21</age>
    </person>
</people>
"""

everyone = et.fromstring(x2_str)
print(everyone.tag) # 부모 element
print()

for one in everyone.findall("person") :
    name = one.findtext("name")
    job = one.findtext("job")
    age = one.findtext("age")
    print(name)
    print(job)
    print(age)
    print()

people

김태경1
개발자
20

김태경2
댄서
21

In [17]:
# XML을 데이터프레임으로 바로 바꾸는 방법
pd.read_xml(StringIO(x2_str))

   name  job  age
0  김태경1  개발자   20
1  김태경2   댄서   21