# 4가지 keyword
1. API
    * 프로그램 간 데이터를 전달하기 위해 정한 규칙
2. HTTP
    * Web에서 데이터를 주고받기 위한 프로토콜
    * https : http + 보안(security)
3. JSON
    * 데이터 전달 포맷
    * 장점 : HTML이나 XML보다 사람이 읽기 편하고 간단하게 python 객체로 변환할 수 있음
4. XML
    * JSON보다 조금 ㅈ아황하지만 사람이 이해하기 쉬운 구조적인 포맷
    * python에서 기본적으로 제공되는 xml 패키지를 사용하여 XML 문서에 있는 엘리먼트를 탐색할 수 있음
    * pandas의 경우 `read_xml()`함수를 사용하여 데이터프레임으로 바꿀 수 있음

# 핵심 함수 및 매서드
* `json.dumps()` : python 객체 -> JSON 문자열 변환
* `json.loads()` : JSON 문자열 -> python 객체
* `pandas.read_json()` : JSON 문자열 -> pandas 시리즈 or 데이터프레임
* `xml.etree.ElementTree.fromstring()` : XML 문자열 -> xml.etree.ElementTree.Element 클래스 객체 반환
* `xml.etree.ElementTree.Element.findtext()` : 지정한 tag name과 맞는 첫 번째 자식 element의 text를 반환
* `xml.etree.ElementTree.Element.findall()` : 지정한 tag name과 맞는 모든 자식 element를 반환
* `requests.get()` : HTTP GET 방식으로 URL 호출 및 requests.Response 객체 반환
* `requests.Response.json()` : 응답받은 JSON 문자열 -> python 객체로 변환하여 반환

In [1]:
# dictionary 생성
d = {"name" : "김태경"}
print(d)
print(type(d))
print(d["name"])

{'name': '김태경'}
<class 'dict'>
김태경

In [2]:
# python 객체를 json 문자열로 변환
import json

# json.dumps()함수는 아스키 문자 외의 다른 문자를 16진수로 출력하기 때문에 한글이 제대로 보이지 않음
d_str = json.dumps(d)
print(d_str)

# json.dumps()함수에서 한글을 보기 위해서 ensure_ascii 매개변수를 False로 설정
d_str = json.dumps(d, ensure_ascii=False)
print(d_str)
print(type(d_str))

{"name": "\uae40\ud0dc\uacbd"}
{"name": "김태경"}
<class 'str'>

In [3]:
# json 문자열을 python 객체로 변환
d2 = json.loads(d_str)

print(d2)
print(type(d2))

{'name': '김태경'}
<class 'dict'>

In [4]:
# 여러 항목을 가진 json 문자열을 python 객체로 변환
d3 = json.loads('{"name" : "김태경", "job" : ["개발자", "댄서"], "age" : 20}')

print(d3)
print(d3["name"])
print(type(d3["job"]))
print(d3["job"][1])
print(d3["age"])
print(type(d3))

{'name': '김태경', 'job': ['개발자', '댄서'], 'age': 20}
김태경
<class 'list'>
댄서
20
<class 'dict'>

In [5]:
d4_str = """
[
    {"name" : "김태경1", "job" : "개발자", "age" : 20},
    {"name" : "김태경2", "job" : "댄서", "age" : 21}
]
"""

d4 = json.loads(d4_str)
print(d4[0]["name"])

김태경1

In [6]:
# json 문자열을 데이터프레임으로 변환하는 방법 1 - 문자열을 바로 데이터프레임으로 변환
from io import StringIO
import pandas as pd

pd.read_json(StringIO(d4_str))

   name  job  age
0  김태경1  개발자   20
1  김태경2   댄서   21

In [7]:
# json 문자열을 데이터프레임으로 변환하는 방법 2 - 문자열을 python 객체로 변환 후 데이터프레임으로 변환
pd.DataFrame(d4)

   name  job  age
0  김태경1  개발자   20
1  김태경2   댄서   21

In [8]:
# XML문자열을 python 객체로 변환

import xml.etree.ElementTree as et

# json pkg는 json 문자열을 python 객체로 변환
# fromstring() 함수가 반환하는 객체는 단순 python 객체가 아닌 ElementTree 모듈 아래에 정의된 Element 클래스의 객체

x_str = """
<info>
    <name>김태경</name>
    <job>개발자</job>
    <age>20</age>
</info>
"""

my_info = et.fromstring(x_str)

print(my_info)
print(type(my_info))

<Element 'info' at 0x000001AAB92012B0>
<class 'xml.etree.ElementTree.Element'>

In [9]:
# my_info 객체는 x_str에서 가장 먼저 등장하는 부모 element인 info에 해당
# my_info 객체의 tag 속성을 출력하면 element 이름 확인 가능
print(my_info.tag)

info

In [10]:
# 자식 element 확인 방법

# 1. my_info element의 자식 element 구하기
info_childs = list(my_info)
print(info_childs)
print()

# 2. 각각의 자식 element에 담긴 text를 읽어오기
name, job, age = info_childs
print(name.text)
print(job.text)
print(age.text)

[<Element 'name' at 0x000001AAB9201300>, <Element 'job' at 0x000001AAB92013A0>, <Element 'age' at 0x000001AAB9201440>]

김태경
개발자
20

In [11]:
# 자식 element가 일정하다는 보장이 없기 때문에 위와 같이 순서대로 자식 element를 찾는 것은 위험함
# findtext() method에서 찾으려는 tag를 넣어주면 해당 element를 찾아서 text로 변환
name = my_info.findtext("name")
job = my_info.findtext("job")
age = my_info.findtext("age")

print(name)
print(job)
print(age)

김태경
개발자
20

In [12]:
# 여러 자식 element 확인
x2_str = """
<people>
    <person>
        <name>김태경1</name>
        <job>개발자</job>
        <age>20</age>
    </person>
    <person>
        <name>김태경2</name>
        <job>댄서</job>
        <age>21</age>
    </person>
</people>
"""

everyone = et.fromstring(x2_str)
print(everyone.tag) # 부모 element
print()

for one in everyone.findall("person") :
    name = one.findtext("name")
    job = one.findtext("job")
    age = one.findtext("age")
    print(name)
    print(job)
    print(age)
    print()

people

김태경1
개발자
20

김태경2
댄서
21

In [13]:
# XML을 데이터프레임으로 바로 바꾸는 방법
pd.read_xml(StringIO(x2_str))

   name  job  age
0  김태경1  개발자   20
1  김태경2   댄서   21

In [ ]:
# API key를 환경변수로 설정하고 불러오는 방법
import os
from dotenv import load_dotenv

load_dotenv()
API_KEY = os.getenv("API_KEY")

# API key로 URL
import requests

url = "https://data4library.kr/api/loanItemSrch?format=json&startDt=2021-04-01&endDt=2021-04-30&authKey={}".format(API_KEY)
r = requests.get(url) # url을 HTTP GET 방식으로 호출 -> requests.Response 객체 반환

print(type(r))
print(r)

{'response': {'request': {'startDt': '2021-04-01', 'endDt': '2021-04-30', 'pageNo': 1, 'pageSize': 200, 'format': 'json'}, 'resultNum': 200, 'numFound': 5000, 'docs': [{'doc': {'no': 1, 'ranking': '1', 'bookname': '달러구트 꿈 백화점 :주문하신 꿈은 매진입니다 ', 'authors': '지은이: 이미예', 'publisher': '팩토리나인', 'publication_year': '2020', 'isbn13': '9791165341909', 'addition_symbol': '03810', 'vol': '', 'class_no': '813.7', 'class_nm': '문학 > 한국문학 > 소설', 'bookImageURL': 'https://image.aladin.co.kr/product/24512/70/cover/k392630952_1.jpg', 'bookDtlUrl': 'https://data4library.kr/bookV?seq=5707051', 'loan_count': '2894'}}, {'doc': {'no': 2, 'ranking': '2', 'bookname': '아몬드 :손원평 장편소설 ', 'authors': '지은이: 손원평', 'publisher': '창비', 'publication_year': '2017', 'isbn13': '9788936434267', 'addition_symbol': '03810', 'vol': '', 'class_no': '813.7', 'class_nm': '문학 > 한국문학 > 소설', 'bookImageURL': 'http://image.aladin.co.kr/product/16839/4/cover/k492534773_1.jpg', 'bookDtlUrl': 'https://data4library.kr/bookV?seq=3423096', 'loan_count': '2841'}}, {'doc': {'no': 3, 'ranking': '3', 'bookname': '(추리 천재) 엉덩이 탐정', 'authors': '트롤 글·그림 ;김정화 옮김', 'publisher': '미래엔', 'publication_year': '2016', 'isbn13': '9791164134090', 'addition_symbol': '74830', 'vol': '9', 'class_no': '833.6', 'class_nm': '문학 > 일본문학 > 소설', 'bookImageURL': 'https://image.aladin.co.kr/product/22712/95/cover/k102636135_1.jpg', 'bookDtlUrl': 'https://data4library.kr/bookV?seq=5581788', 'loan_count': '2462'}}, {'doc': {'no': 4, 'ranking': '4', 'bookname': '(추리 천재) 엉덩이 탐정', 'authors': '트롤 글·그림 ;김정화 옮김', 'publisher': '미래엔', 'publication_year': '2016', 'isbn13': '9791162339466', 'addition_symbol': '74830', 'vol': '7', 'class_no': '833.6', 'class_nm': '문학 > 일본문학 > 소설', 'bookImageURL': 'https://image.aladin.co.kr/product/17457/14/cover/k792534209_1.jpg', 'bookDtlUrl': 'https://data4library.kr/bookV?seq=5245643', 'loan_count': '2355'}}, {'doc': {'no': 5, 'ranking': '5', 'bookname': '(추리 천재) 엉덩이 탐정', 'authors': '트롤 글·그림 ;김정화 옮김', 'publisher': '미래엔', 'publication_year': '2016', 'isbn13': '9791164131914', 'addition_symbol': '74830', 'vol': '8', 'class_no': '833.6', 'class_nm': '문학 > 일본문학 > 소설', 'bookImageURL': 'https://image.aladin.co.kr/product/19874/27/cover/k432635431_1.jpg', 'bookDtlUrl': 'https://data4library.kr/bookV?seq=5448424', 'loan_count': '2268'}}, {'doc': {'no': 6, 'ranking': '6', 'bookname': '흔한남매', 'authors': '원작: 흔한남매 ;그림: 유난희', 'publisher': '미래엔', 'publication_year': '2019', 'isbn13': '9791164134267', 'addition_symbol': '77810', 'vol': '3', 'class_no': '810', 'class_nm': '문학 > 한국문학 > 한국문학', 'bookImageURL': 'https://image.aladin.co.kr/product/22327/46/cover/k782636924_1.jpg', 'bookDtlUrl': 'https://data4library.kr/bookV?seq=5569013', 'loan_count': '2213'}}, {'doc': {'no': 7, 'ranking': '7', 'bookname': '(추리 천재) 엉덩이 탐정', 'authors': '트롤 글·그림 ;김정화 옮김', 'publisher': '미래엔', 'publication_year': '2016', 'isbn13': '9791162332542', 'addition_symbol': '74830', 'vol': '5', 'class_no': '833.6', 'class_nm': '문학 > 일본문학 > 소설', 'bookImageURL': 'https://bookthumb-phinf.pstatic.net/cover/129/756/12975600.jpg?type=m1&udate=20180126', 'bookDtlUrl': 'https://data4library.kr/bookV?seq=3676788', 'loan_count': '2202'}}, {'doc': {'no': 8, 'ranking': '8', 'bookname': '시선으로부터, :정세랑 장편소설 ', 'authors': '지은이: 정세랑', 'publisher': '문학동네', 'publication_year': '2020', 'isbn13': '9788954672214', 'addition_symbol': '03810', 'vol': '', 'class_no': '813.7', 'class_nm': '문학 > 한국문학 > 소설', 'bookImageURL': 'https://image.aladin.co.kr/product/24131/37/cover/8954672213_1.jpg', 'bookDtlUrl': 'https://data4library.kr/bookV?seq=5674475', 'loan_count': '2183'}}, {'doc': {'no': 9, 'ranking': '9', 'bookname': '(이상한 과자 가게) 전천당', 'authors': '히로시마 레이코 글 ;김정화 옮김', 'publisher': '길벗스쿨', 'publication_year': '2019', 'isbn13': '9791164060481', 'addition_symbol': '74830', 'vol': '1', 'class_no': '833.6', 'class_nm': '문학 > 일본문학 > 소설', 'bookImageURL': 'https://image.aladin.co.kr/product/19610/47/cover/k282635522_1.jpg', 'bookDtlUrl': 'https://data4library.kr/bookV?seq=5439175', 'loan_count': '2180'}}, {'doc': {'no': 10, 'ranking': '10', 'bookname': '(추리 천재) 엉덩이 탐정', 'authors': '트롤 글·그림 ;김정화 옮김', 'publisher': '미래엔', 'publication_year': '2016', 'isbn13': '9788937848247', 'addition_symbol': '74830', 'vol': '4', 'class_no': '833.6', 'class_nm': '문학 > 일본문학 > 소설', 'bookImageURL': 'https://bookthumb-phinf.pstatic.net/cover/124/953/12495377.jpg?type=m1&udate=20170829', 'bookDtlUrl': 'https://data4library.kr/bookV?seq=3541426', 'loan_count': '2168'}}, {'doc': {'no': 11, 'ranking': '11', 'bookname': '(추리 천재) 엉덩이 탐정', 'authors': '트롤 글·그림 ;김정화 옮김', 'publisher': '미래엔', 'publication_year': '2016', 'isbn13': '9791162335123', 'addition_symbol': '74830', 'vol': '6', 'class_no': '833.6', 'class_nm': '문학 > 일본문학 > 소설', 'bookImageURL': 'https://bookthumb-phinf.pstatic.net/cover/135/613/13561388.jpg?type=m1&udate=20180619', 'bookDtlUrl': 'https://data4library.kr/bookV?seq=3746485', 'loan_count': '2160'}}, {'doc': {'no': 12, 'ranking': '12', 'bookname': '(추리 천재) 엉덩이 탐정', 'authors': '트롤 글·그림 ;김정화 옮김', 'publisher': '미래엔', 'publication_year': '2016', 'isbn13': '9791164137053', 'addition_symbol': '74830', 'vol': '10', 'class_no': '833.6', 'class_nm': '문학 > 일본문학 > 소설', 'bookImageURL': 'https://image.aladin.co.kr/product/25801/42/cover/k252736232_1.jpg', 'bookDtlUrl': 'https://data4library.kr/bookV?seq=5827187', 'loan_count': '2152'}}, {'doc': {'no': 13, 'ranking': '13', 'bookname': '(추리 천재) 엉덩이 탐정', 'authors': '트롤 글·그림 ;김정화 옮김', 'publisher': '미래엔', 'publication_year': '2016', 'isbn13': '9788937889714', 'addition_symbol': '74830', 'vol': '3', 'class_no': '833.6', 'class_nm': '문학 > 일본문학 > 소설', 'bookImageURL': 'http://image.aladin.co.kr/product/10644/93/cover/8937889714_1.jpg', 'bookDtlUrl': 'https://data4library.kr/bookV?seq=3425818', 'loan_count': '2127'}}, {'doc': {'no': 14, 'ranking': '14', 'bookname': '흔한남매', 'authors': '원작: 흔한남매 ;그림: 유난희', 'publisher': '미래엔', 'publication_year': '2019', 'isbn13': '9791164135592', 'addition_symbol': '77810', 'vol': '5', 'class_no': '810', 'class_nm': '문학 > 한국문학 > 한국문학', 'bookImageURL': 'https://image.aladin.co.kr/product/24307/73/cover/k822630592_2.jpg', 'bookDtlUrl': 'https://data4library.kr/bookV?seq=5686627', 'loan_count': '2125'}}, {'doc': {'no': 15, 'ranking': '15', 'bookname': '흔한남매', 'authors': '원작: 흔한남매 ;그림: 유난희', 'publisher': '미래엔', 'publication_year': '2019', 'isbn13': '9791164131686', 'addition_symbol': '77810', 'vol': '1', 'class_no': '810', 'class_nm': '문학 > 한국문학 > 한국문학', 'bookImageURL': 'https://image.aladin.co.kr/product/19404/61/cover/k712635217_1.jpg', 'bookDtlUrl': 'https://data4library.kr/bookV?seq=5429011', 'loan_count': '2115'}}, {'doc': {'no': 16, 'ranking': '16', 'bookname': '(이상한 과자 가게) 전천당', 'authors': '히로시마 레이코 글 ;김정화 옮김', 'publisher': '길벗스쿨', 'publication_year': '2019', 'isbn13': '9791164060498', 'addition_symbol': '74830', 'vol': '2', 'class_no': '833.6', 'class_nm': '문학 > 일본문학 > 소설', 'bookImageURL': 'https://image.aladin.co.kr/product/19612/74/cover/k772635522_1.jpg', 'bookDtlUrl': 'https://data4library.kr/bookV?seq=5439173', 'loan_count': '2101'}}, {'doc': {'no': 17, 'ranking': '17', 'bookname': '(이상한 과자 가게) 전천당', 'authors': '히로시마 레이코 글 ;김정화 옮김', 'publisher': '길벗스쿨', 'publication_year': '2019', 'isbn13': '9791164060931', 'addition_symbol': '74830', 'vol': '3', 'class_no': '833.6', 'class_nm': '문학 > 일본문학 > 소설', 'bookImageURL': 'https://image.aladin.co.kr/product/21439/64/cover/k142636199_1.jpg', 'bookDtlUrl': 'https://data4library.kr/bookV?seq=5518312', 'loan_count': '2086'}}, {'doc': {'no': 18, 'ranking': '18', 'bookname': '어떻게 말해줘야 할까 :오은영의 현실밀착 육아회화 ', 'authors': '글: 오은영 ;그림: 차상미', 'publisher': '김영사', 'publication_year': '2020', 'isbn13': '9788934986652', 'addition_symbol': '13590', 'vol': '', 'class_no': '598.1', 'class_nm': '기술과학 > 가정학 및 가정생활 > 육아', 'bookImageURL': 'https://image.aladin.co.kr/product/25313/30/cover/8934986654_1.jpg', 'bookDtlUrl': 'https://data4library.kr/bookV?seq=5778286', 'loan_count': '2085'}}, {'doc': {'no': 19, 'ranking': '19', 'bookname': '흔한남매', 'authors': '원작: 흔한남매 ;그림: 유난희', 'publisher': '미래엔', 'publication_year': '2019', 'isbn13': '9791164132454', 'addition_symbol': '77810', 'vol': '2', 'class_no': '810', 'class_nm': '문학 > 한국문학 > 한국문학', 'bookImageURL': 'https://image.aladin.co.kr/product/20398/4/cover/k002635150_1.jpg', 'bookDtlUrl': 'https://data4library.kr/bookV?seq=5463101', 'loan_count': '2073'}}, {'doc': {'no': 20, 'ranking': '20', 'bookname': '흔한남매', 'authors': '원작: 흔한남매 ;그림: 유난희', 'publisher': '미래엔', 'publication_year': '2019', 'isbn13': '9791164134847', 'addition_symbol': '77810', 'vol': '4', 'class_no': '810', 'class_nm': '문학 > 한국문학 > 한국문학', 'bookImageURL': 'https://image.aladin.co.kr/product/23568/96/cover/k992638123_1.jpg', 'bookDtlUrl': 'https://data4library.kr/bookV?seq=5635121', 'loan_count': '2069'}}, {'doc': {'no': 21, 'ranking': '21', 'bookname': '(추리 천재) 엉덩이 탐정', 'authors': '트롤 글·그림 ;김정화 옮김', 'publisher': '미래엔', 'publication_year': '2016', 'isbn13': '9788937853470', 'addition_symbol': '74830', 'vol': '2', 'class_no': '833.6', 'class_nm': '문학 > 일본문학 > 소설', 'bookImageURL': 'https://bookthumb-phinf.pstatic.net/cover/113/327/11332741.jpg?type=m1&udate=20161209', 'bookDtlUrl': 'https://data4library.kr/bookV?seq=3392650', 'loan_count': '2059'}}, {'doc': {'no': 22, 'ranking': '22', 'bookname': '(이상한 과자 가게) 전천당', 'authors': '히로시마 레이코 글 ;김정화 옮김', 'publisher': '길벗스쿨', 'publication_year': '2019', 'isbn13': '9791164062270', 'addition_symbol': '74830', 'vol': '7', 'class_no': '833.6', 'class_nm': '문학 > 일본문학 > 소설', 'bookImageURL': 'https://image.aladin.co.kr/product/24394/32/cover/k412630313_1.jpg', 'bookDtlUrl': 'https://data4library.kr/bookV?seq=5699900', 'loan_count': '2046'}}, {'doc': {'no': 23, 'ranking': '23', 'bookname': '(이상한 과자 가게) 전천당', 'authors': '히로시마 레이코 글 ;김정화 옮김', 'publisher': '길벗스쿨', 'publication_year': '2019', 'isbn13': '9791164062065', 'addition_symbol': '74830', 'vol': '5', 'class_no': '833.6', 'class_nm': '문학 > 일본문학 > 소설', 'bookImageURL': 'https://image.aladin.co.kr/product/23450/15/cover/k522638585_1.jpg', 'bookDtlUrl': 'https://data4library.kr/bookV?seq=5609753', 'loan_count': '2042'}}, {'doc': {'no': 24, 'ranking': '24', 'bookname': '(추리 천재) 엉덩이 탐정', 'authors': '트롤 글·그림 ;김정화 옮김', 'publisher': '미래엔', 'publication_year': '2016', 'isbn13': '9788937838750', 'addition_symbol': '74830', 'vol': '1', 'class_no': '833.6', 'class_nm': '문학 > 일본문학 > 소설', 'bookImageURL': 'http://image.aladin.co.kr/product/8920/23/cover/8937838753_1.jpg', 'bookDtlUrl': 'https://data4library.kr/bookV?seq=3272507', 'loan_count': '2039'}}, {'doc': {'no': 25, 'ranking': '25', 'bookname': '(이상한 과자 가게) 전천당', 'authors': '히로시마 레이코 글 ;김정화 옮김', 'publisher': '길벗스쿨', 'publication_year': '2019', 'isbn13': '9791164060948', 'addition_symbol': '74830', 'vol': '4', 'class_no': '833.6', 'class_nm': '문학 > 일본문학 > 소설', 'bookImageURL': 'https://image.aladin.co.kr/product/21439/72/cover/k272636199_1.jpg', 'bookDtlUrl': 'https://data4library.kr/bookV?seq=5518313', 'loan_count': '2036'}}, {'doc': {'no': 26, 'ranking': '26', 'bookname': '(이상한 과자 가게) 전천당', 'authors': '히로시마 레이코 글 ;김정화 옮김', 'publisher': '길벗스쿨', 'publication_year': '2019', 'isbn13': '9791164062072', 'addition_symbol': '74830', 'vol': '6', 'class_no': '833.6', 'class_nm': '문학 > 일본문학 > 소설', 'bookImageURL': 'https://image.aladin.co.kr/product/23450/17/cover/k692638585_1.jpg', 'bookDtlUrl': 'https://data4library.kr/bookV?seq=5609754', 'loan_count': '2018'}}, {'doc': {'no': 27, 'ranking': '27', 'bookname': '(이상한 과자 가게) 전천당', 'authors': '히로시마 레이코 글 ;김정화 옮김', 'publisher': '길벗스쿨', 'publication_year': '2019', 'isbn13': '9791164062287', 'addition_symbol': '74830', 'vol': '8', 'class_no': '833.6', 'class_nm': '문학 > 일본문학 > 소설', 'bookImageURL': 'https://image.aladin.co.kr/product/25020/81/cover/k782632928_1.jpg', 'bookDtlUrl': 'https://data4library.kr/bookV?seq=5746636', 'loan_count': '2008'}}, {'doc': {'no': 28, 'ranking': '28', 'bookname': '(이상한 과자 가게) 전천당', 'authors': '히로시마 레이코 글 ;김정화 옮김', 'publisher': '길벗스쿨', 'publication_year': '2019', 'isbn13': '9791164062898', 'addition_symbol': '74830', 'vol': '9', 'class_no': '833.6', 'class_nm': '문학 > 일본문학 > 소설', 'bookImageURL': 'https://image.aladin.co.kr/product/25732/47/cover/k092736875_1.jpg', 'bookDtlUrl': 'https://data4library.kr/bookV?seq=5823468', 'loan_count': '1988'}}, {'doc': {'no': 29, 'ranking': '29', 'bookname': '나미야 잡화점의 기적 :히가시노 게이고 장편소설 ', 'authors': '지은이: 히가시노 게이고 ;옮긴이: 양윤옥', 'publisher': '현대문학', 'publication_year': '2012', 'isbn13': '9788972756194', 'addition_symbol': '03830', 'vol': '', 'class_no': '833.6', 'class_nm': '문학 > 일본문학 > 소설', 'bookImageURL': 'http://image.aladin.co.kr/product/15848/6/cover/k622533431_1.jpg', 'bookDtlUrl': 'https://data4library.kr/bookV?seq=1902173', 'loan_count': '1987'}}, {'doc': {'no': 30, 'ranking': '30', 'bookname': '흔한남매', 'authors': '원작: 흔한남매 ;그림: 유난희', 'publisher': '미래엔', 'publication_year': '2019', 'isbn13': '9791164136261', 'addition_symbol': '77810', 'vol': '6', 'class_no': '810', 'class_nm': '문학 > 한국문학 > 한국문학', 'bookImageURL': 'https://image.aladin.co.kr/product/25301/95/cover/k062633309_1.jpg', 'bookDtlUrl': 'https://data4library.kr/bookV?seq=5777315', 'loan_count': '1946'}}, {'doc': {'no': 31, 'ranking': '31', 'bookname': '수박 수영장 :안녕달 그림책 ', 'authors': '지은이: 안녕달', 'publisher': '창비', 'publication_year': '2015', 'isbn13': '9788936446819', 'addition_symbol': '77810', 'vol': '', 'class_no': '813.7', 'class_nm': '문학 > 한국문학 > 소설', 'bookImageURL': 'https://bookthumb-phinf.pstatic.net/cover/093/451/09345174.jpg?type=m1&udate=20180718', 'bookDtlUrl': 'https://data4library.kr/bookV?seq=2396971', 'loan_count': '1911'}}, {'doc': {'no': 32, 'ranking': '32', 'bookname': '우리가 빛의 속도로 갈 수 없다면 :김초엽 소설 ', 'authors': '지은이: 김초엽', 'publisher': '허블', 'publication_year': '2019', 'isbn13': '9791190090018', 'addition_symbol': '03810', 'vol': '', 'class_no': '813.7', 'class_nm': '문학 > 한국문학 > 소설', 'bookImageURL': 'https://image.aladin.co.kr/product/19359/16/cover/s972635417_1.jpg', 'bookDtlUrl': 'https://data4library.kr/bookV?seq=5430429', 'loan_count': '1815'}}, {'doc': {'no': 33, 'ranking': '33', 'bookname': '설민석의 한국사 대모험', 'authors': '글: 설민석,그림: 정현희', 'publisher': '휴먼큐브', 'publication_year': '2017', 'isbn13': '9791165382674', 'addition_symbol': '74910', 'vol': '14', 'class_no': '911', 'class_nm': '역사 > 아시아(아세아) > 한국', 'bookImageURL': 'https://image.aladin.co.kr/product/24258/33/cover/k742630570_1.jpg', 'bookDtlUrl': 'https://data4library.kr/bookV?seq=5686995', 'loan_count': '1814'}}, {'doc': {'no': 34, 'ranking': '34', 'bookname': '설민석의 한국사 대모험', 'authors': '글: 설민석,그림: 정현희', 'publisher': '휴먼큐브', 'publication_year': '2017', 'isbn13': '9791195794799', 'addition_symbol': '74910', 'vol': '1', 'class_no': '911', 'class_nm': '역사 > 아시아(아세아) > 한국', 'bookImageURL': 'http://image.aladin.co.kr/product/10016/32/cover/k512536564_2.jpg', 'bookDtlUrl': 'https://data4library.kr/bookV?seq=3405847', 'loan_count': '1803'}}, {'doc': {'no': 35, 'ranking': '35', 'bookname': '돈의 속성 :최상위 부자가 말하는 돈에 대한 모든 것 ', 'authors': '지은이: 김승호', 'publisher': 'Snowfox(스노우폭스북스)', 'publication_year': '2020', 'isbn13': '9791188331796', 'addition_symbol': '03320', 'vol': '', 'class_no': '327.04', 'class_nm': '사회과학 > 경제학 > 금융', 'bookImageURL': 'https://image.aladin.co.kr/product/24191/64/cover/k562639753_1.jpg', 'bookDtlUrl': 'https://data4library.kr/bookV?seq=5678862', 'loan_count': '1783'}}, {'doc': {'no': 36, 'ranking': '36', 'bookname': '당근 유치원 ', 'authors': '지은이: 안녕달', 'publisher': '창비', 'publication_year': '2020', 'isbn13': '9788936455484', 'addition_symbol': '77810', 'vol': '', 'class_no': '813.7', 'class_nm': '문학 > 한국문학 > 소설', 'bookImageURL': 'https://image.aladin.co.kr/product/24011/82/cover/8936455486_1.jpg', 'bookDtlUrl': 'https://data4library.kr/bookV?seq=5666934', 'loan_count': '1781'}}, {'doc': {'no': 37, 'ranking': '37', 'bookname': '어린이라는 세계 :김소영 에세이 ', 'authors': '지은이: 김소영', 'publisher': '사계절(사계절출판사)', 'publication_year': '2020', 'isbn13': '9791160946918', 'addition_symbol': '03810', 'vol': '', 'class_no': '818', 'class_nm': '문학 > 한국문학 > 르포르타주 및 기타', 'bookImageURL': 'https://image.aladin.co.kr/product/25509/75/cover/k132633125_1.jpg', 'bookDtlUrl': 'https://data4library.kr/bookV?seq=5795911', 'loan_count': '1762'}}, {'doc': {'no': 38, 'ranking': '38', 'bookname': '설민석의 한국사 대모험', 'authors': '글: 설민석,그림: 정현희', 'publisher': '휴먼큐브', 'publication_year': '2017', 'isbn13': '9791165382650', 'addition_symbol': '74910', 'vol': '13', 'class_no': '911', 'class_nm': '역사 > 아시아(아세아) > 한국', 'bookImageURL': 'https://image.aladin.co.kr/product/23535/70/cover/k662638920_1.jpg', 'bookDtlUrl': 'https://data4library.kr/bookV?seq=5623860', 'loan_count': '1752'}}, {'doc': {'no': 39, 'ranking': '39', 'bookname': '설민석의 한국사 대모험', 'authors': '글: 설민석,그림: 정현희', 'publisher': '휴먼큐브', 'publication_year': '2017', 'isbn13': '9791165382704', 'addition_symbol': '74910', 'vol': '15', 'class_no': '911', 'class_nm': '역사 > 아시아(아세아) > 한국', 'bookImageURL': 'https://image.aladin.co.kr/product/25259/92/cover/k052633102_1.jpg', 'bookDtlUrl': 'https://data4library.kr/bookV?seq=5776020', 'loan_count': '1745'}}, {'doc': {'no': 40, 'ranking': '40', 'bookname': '공정하다는 착각 :능력주의는 모두에게 같은 기회를 제공하는가 ', 'authors': '마이클 샌델 지음 ;함규진 옮김', 'publisher': '미래엔', 'publication_year': '2020', 'isbn13': '9791164136452', 'addition_symbol': '03300', 'vol': '', 'class_no': '332.6', 'class_nm': '사회과학 > 사회학, 사회문제 > 사회조직 및 제도', 'bookImageURL': 'https://image.aladin.co.kr/product/25470/6/cover/k092633826_1.jpg', 'bookDtlUrl': 'https://data4library.kr/bookV?seq=5791228', 'loan_count': '1740'}}, {'doc': {'no': 41, 'ranking': '41', 'bookname': '나의 하루는 4시 30분에 시작된다 :하루를 두 배로 사는 단 하나의 습관 ', 'authors': '김유진 지음', 'publisher': 'Tornado(토네이도)', 'publication_year': '2020', 'isbn13': '9791158511906', 'addition_symbol': '03190', 'vol': '', 'class_no': '325.211', 'class_nm': '사회과학 > 경제학 > 경영관리', 'bookImageURL': 'https://image.aladin.co.kr/product/25306/49/cover/k922633306_1.jpg', 'bookDtlUrl': 'https://data4library.kr/bookV?seq=5778871', 'loan_count': '1703'}}, {'doc': {'no': 42, 'ranking': '42', 'bookname': '파친코 :이민진 장편소설', 'authors': '이민진 지음 ;이미정 옮김', 'publisher': '문학사상', 'publication_year': '2018', 'isbn13': '9788970129815', 'addition_symbol': '04840', 'vol': '1', 'class_no': '843.6', 'class_nm': '문학 > 영미문학 > 소설', 'bookImageURL': 'https://bookthumb-phinf.pstatic.net/cover/134/282/13428208.jpg?type=m1&udate=20180331', 'bookDtlUrl': 'https://data4library.kr/bookV?seq=3723218', 'loan_count': '1701'}}, {'doc': {'no': 43, 'ranking': '43', 'bookname': '설민석의 한국사 대모험', 'authors': '글: 설민석,그림: 정현희', 'publisher': '휴먼큐브', 'publication_year': '2017', 'isbn13': '9791188874460', 'addition_symbol': '74910', 'vol': '12', 'class_no': '911', 'class_nm': '역사 > 아시아(아세아) > 한국', 'bookImageURL': 'https://image.aladin.co.kr/product/21613/51/cover/k122636592_1.jpg', 'bookDtlUrl': 'https://data4library.kr/bookV?seq=5521219', 'loan_count': '1700'}}, {'doc': {'no': 44, 'ranking': '44', 'bookname': '아홉 살 마음 사전 ', 'authors': '박성우 글 ;김효은 그림', 'publisher': '창비', 'publication_year': '2017', 'isbn13': '9788936447014', 'addition_symbol': '73710', 'vol': '', 'class_no': '181', 'class_nm': '철학 > 심리학 > 각론', 'bookImageURL': 'http://image.aladin.co.kr/product/10537/49/cover/8936447017_1.jpg', 'bookDtlUrl': 'https://data4library.kr/bookV?seq=3421838', 'loan_count': '1696'}}, {'doc': {'no': 45, 'ranking': '45', 'bookname': '설민석의 한국사 대모험', 'authors': '글: 설민석,그림: 정현희', 'publisher': '휴먼큐브', 'publication_year': '2017', 'isbn13': '9791196025809', 'addition_symbol': '74910', 'vol': '2', 'class_no': '911', 'class_nm': '역사 > 아시아(아세아) > 한국', 'bookImageURL': 'http://image.aladin.co.kr/product/10227/84/cover/k782536886_2.jpg', 'bookDtlUrl': 'https://data4library.kr/bookV?seq=3412785', 'loan_count': '1689'}}, {'doc': {'no': 46, 'ranking': '46', 'bookname': '고양이 해결사 깜냥', 'authors': '홍민정 동화 ;김재희 그림', 'publisher': '창비', 'publication_year': '2020', 'isbn13': '9788936447694', 'addition_symbol': '74810', 'vol': '1', 'class_no': '813.7', 'class_nm': '문학 > 

{'response': {'request': {'startDt': '2021-04-01',
   'endDt': '2021-04-30',
   'pageNo': 1,
   'pageSize': 200,
   'format': 'json'},
  'resultNum': 200,
  'numFound': 5000,
  'docs': [{'doc': {'no': 1,
     'ranking': '1',
     'bookname': '달러구트 꿈 백화점 :주문하신 꿈은 매진입니다 ',
     'authors': '지은이: 이미예',
     'publisher': '팩토리나인',
     'publication_year': '2020',
     'isbn13': '9791165341909',
     'addition_symbol': '03810',
     'vol': '',
     'class_no': '813.7',
     'class_nm': '문학 > 한국문학 > 소설',
     'bookImageURL': 'https://image.aladin.co.kr/product/24512/70/cover/k392630952_1.jpg',
     'bookDtlUrl': 'https://data4library.kr/bookV?seq=5707051',
     'loan_count': '2894'}},
   {'doc': {'no': 2,
     'ranking': '2',
     'bookname': '아몬드 :손원평 장편소설 ',
     'authors': '지은이: 손원평',
     'publisher': '창비',
     'publication_year': '2017',
     'isbn13': '9788936434267',
     'addition_symbol': '03810',
     'vol': '',
     'class_no': '813.7',
     'class_nm': '문학 > 한국문학 > 소설',
     'bookImageURL': 'http://image.aladin.co.kr/product/16839/4/cover/k492534773_1.jpg',
     'bookDtlUrl': 'https://data4library.kr/bookV?seq=3423096',
     'loan_count': '2841'}},
   {'doc': {'no': 3,
     'ranking': '3',
     'bookname': '(추리 천재) 엉덩이 탐정',
     'authors': '트롤 글·그림 ;김정화 옮김',
     'publisher': '미래엔',
     'publication_year': '2016',
     'isbn13': '9791164134090',
     'addition_symbol': '74830',
     'vol': '9',
     'class_no': '833.6',
     'class_nm': '문학 > 일본문학 > 소설',
     'bookImageURL': 'https://image.aladin.co.kr/product/22712/95/cover/k102636135_1.jpg',
     'bookDtlUrl': 'https://data4library.kr/bookV?seq=5581788',
     'loan_count': '2462'}},
   {'doc': {'no': 4,
     'ranking': '4',
     'bookname': '(추리 천재) 엉덩이 탐정',
     'authors': '트롤 글·그림 ;김정화 옮김',
     'publisher': '미래엔',
     'publication_year': '2016',
     'isbn13': '9791162339466',
     'addition_symbol': '74830',
     'vol': '7',
     'class_no': '833.6',
     'class_nm': '문학 > 일본문학 > 소설',
     'bookImageURL': 'https://image.aladin.co.kr/product/17457/14/cover/k792534209_1.jpg',
     'bookDtlUrl': 'https://data4library.kr/bookV?seq=5245643',
     'loan_count': '2355'}},
   {'doc': {'no': 5,
     'ranking': '5',
     'bookname': '(추리 천재) 엉덩이 탐정',
     'authors': '트롤 글·그림 ;김정화 옮김',
     'publisher': '미래엔',
     'publication_year': '2016',
     'isbn13': '9791164131914',
     'addition_symbol': '74830',
     'vol': '8',
     'class_no': '833.6',
     'class_nm': '문학 > 일본문학 > 소설',
     'bookImageURL': 'https://image.aladin.co.kr/product/19874/27/cover/k432635431_1.jpg',
     'bookDtlUrl': 'https://data4library.kr/bookV?seq=5448424',
     'loan_count': '2268'}},
   {'doc': {'no': 6,
     'ranking': '6',
     'bookname': '흔한남매',
     'authors': '원작: 흔한남매 ;그림: 유난희',
     'publisher': '미래엔',
     'publication_year': '2019',
     'isbn13': '9791164134267',
     'addition_symbol': '77810',
     'vol': '3',
     'class_no': '810',
     'class_nm': '문학 > 한국문학 > 한국문학',
     'bookImageURL': 'https://image.aladin.co.kr/product/22327/46/cover/k782636924_1.jpg',
     'bookDtlUrl': 'https://data4library.kr/bookV?seq=5569013',
     'loan_count': '2213'}},
   {'doc': {'no': 7,
     'ranking': '7',
     'bookname': '(추리 천재) 엉덩이 탐정',
     'authors': '트롤 글·그림 ;김정화 옮김',
     'publisher': '미래엔',
     'publication_year': '2016',
     'isbn13': '9791162332542',
     'addition_symbol': '74830',
     'vol': '5',
     'class_no': '833.6',
     'class_nm': '문학 > 일본문학 > 소설',
     'bookImageURL': 'https://bookthumb-phinf.pstatic.net/cover/129/756/12975600.jpg?type=m1&udate=20180126',
     'bookDtlUrl': 'https://data4library.kr/bookV?seq=3676788',
     'loan_count': '2202'}},
   {'doc': {'no': 8,
     'ranking': '8',
     'bookname': '시선으로부터, :정세랑 장편소설 ',
     'authors': '지은이: 정세랑',
     'publisher': '문학동네',
     'publication_year': '2020',
     'isbn13': '9788954672214',
     'addition_symbol': '03810',
     'vol': '',
     'class_no': '813.7',
     'class_nm': '문학 > 한국문학 > 소설',
     'bookImageURL': 'https://image.aladin.co.kr/product/24131/37/cover/8954672213_1.jpg',
     'bookDtlUrl': 'https://data4library.kr/bookV?seq=5674475',
     'loan_count': '2183'}},
   {'doc': {'no': 9,
     'ranking': '9',
     'bookname': '(이상한 과자 가게) 전천당',
     'authors': '히로시마 레이코 글 ;김정화 옮김',
     'publisher': '길벗스쿨',
     'publication_year': '2019',
     'isbn13': '9791164060481',
     'addition_symbol': '74830',
     'vol': '1',
     'class_no': '833.6',
     'class_nm': '문학 > 일본문학 > 소설',
     'bookImageURL': 'https://image.aladin.co.kr/product/19610/47/cover/k282635522_1.jpg',
     'bookDtlUrl': 'https://data4library.kr/bookV?seq=5439175',
     'loan_count': '2180'}},
   {'doc': {'no': 10,
     'ranking': '10',
     'bookname': '(추리 천재) 엉덩이 탐정',
     'authors': '트롤 글·그림 ;김정화 옮김',
     'publisher': '미래엔',
     'publication_year': '2016',
     'isbn13': '9788937848247',
     'addition_symbol': '74830',
     'vol': '4',
     'class_no': '833.6',
     'class_nm': '문학 > 일본문학 > 소설',
     'bookImageURL': 'https://bookthumb-phinf.pstatic.net/cover/124/953/12495377.jpg?type=m1&udate=20170829',
     'bookDtlUrl': 'https://data4library.kr/bookV?seq=3541426',
     'loan_count': '2168'}},
   {'doc': {'no': 11,
     'ranking': '11',
     'bookname': '(추리 천재) 엉덩이 탐정',
     'authors': '트롤 글·그림 ;김정화 옮김',
     'publisher': '미래엔',
     'publication_year': '2016',
     'isbn13': '9791162335123',
     'addition_symbol': '74830',
     'vol': '6',
     'class_no': '833.6',
     'class_nm': '문학 > 일본문학 > 소설',
     'bookImageURL': 'https://bookthumb-phinf.pstatic.net/cover/135/613/13561388.jpg?type=m1&udate=20180619',
     'bookDtlUrl': 'https://data4library.kr/bookV?seq=3746485',
     'loan_count': '2160'}},
   {'doc': {'no': 12,
     'ranking': '12',
     'bookname': '(추리 천재) 엉덩이 탐정',
     'authors': '트롤 글·그림 ;김정화 옮김',
     'publisher': '미래엔',
     'publication_year': '2016',
     'isbn13': '9791164137053',
     'addition_symbol': '74830',
     'vol': '10',
     'class_no': '833.6',
     'class_nm': '문학 > 일본문학 > 소설',
     'bookImageURL': 'https://image.aladin.co.kr/product/25801/42/cover/k252736232_1.jpg',
     'bookDtlUrl': 'https://data4library.kr/bookV?seq=5827187',
     'loan_count': '2152'}},
   {'doc': {'no': 13,
     'ranking': '13',
     'bookname': '(추리 천재) 엉덩이 탐정',
     'authors': '트롤 글·그림 ;김정화 옮김',
     'publisher': '미래엔',
     'publication_year': '2016',
     'isbn13': '9788937889714',
     'addition_symbol': '74830',
     'vol': '3',
     'class_no': '833.6',
     'class_nm': '문학 > 일본문학 > 소설',
     'bookImageURL': 'http://image.aladin.co.kr/product/10644/93/cover/8937889714_1.jpg',
     'bookDtlUrl': 'https://data4library.kr/bookV?seq=3425818',
     'loan_count': '2127'}},
   {'doc': {'no': 14,
     'ranking': '14',
     'bookname': '흔한남매',
     'authors': '원작: 흔한남매 ;그림: 유난희',
     'publisher': '미래엔',
     'publication_year': '2019',
     'isbn13': '9791164135592',
     'addition_symbol': '77810',
     'vol': '5',
     'class_no': '810',
     'class_nm': '문학 > 한국문학 > 한국문학',
     'bookImageURL': 'https://image.aladin.co.kr/product/24307/73/cover/k822630592_2.jpg',
     'bookDtlUrl': 'https://data4library.kr/bookV?seq=5686627',
     'loan_count': '2125'}},
   {'doc': {'no': 15,
     'ranking': '15',
     'bookname': '흔한남매',
     'authors': '원작: 흔한남매 ;그림: 유난희',
     'publisher': '미래엔',
     'publication_year': '2019',
     'isbn13': '9791164131686',
     'addition_symbol': '77810',
     'vol': '1',
     'class_no': '810',
     'class_nm': '문학 > 한국문학 > 한국문학',
     'bookImageURL': 'https://image.aladin.co.kr/product/19404/61/cover/k712635217_1.jpg',
     'bookDtlUrl': 'https://data4library.kr/bookV?seq=5429011',
     'loan_count': '2115'}},
   {'doc': {'no': 16,
     'ranking': '16',
     'bookname': '(이상한 과자 가게) 전천당',
     'authors': '히로시마 레이코 글 ;김정화 옮김',
     'publisher': '길벗스쿨',
     'publication_year': '2019',
     'isbn13': '9791164060498',
     'addition_symbol': '74830',
     'vol': '2',
     'class_no': '833.6',
     'class_nm': '문학 > 일본문학 > 소설',
     'bookImageURL': 'https://image.aladin.co.kr/product/19612/74/cover/k772635522_1.jpg',
     'bookDtlUrl': 'https://data4library.kr/bookV?seq=5439173',
     'loan_count': '2101'}},
   {'doc': {'no': 17,
     'ranking': '17',
     'bookname': '(이상한 과자 가게) 전천당',
     'authors': '히로시마 레이코 글 ;김정화 옮김',
     'publisher': '길벗스쿨',
     'publication_year': '2019',
     'isbn13': '9791164060931',
     'addition_symbol': '74830',
     'vol': '3',
     'class_no': '833.6',
     'class_nm': '문학 > 일본문학 > 소설',
     'bookImageURL': 'https://image.aladin.co.kr/product/21439/64/cover/k142636199_1.jpg',
     'bookDtlUrl': 'https://data4library.kr/bookV?seq=5518312',
     'loan_count': '2086'}},
   {'doc': {'no': 18,
     'ranking': '18',
     'bookname': '어떻게 말해줘야 할까 :오은영의 현실밀착 육아회화 ',
     'authors': '글: 오은영 ;그림: 차상미',
     'publisher': '김영사',
     'publication_year': '2020',
     'isbn13': '9788934986652',
     'addition_symbol': '13590',
     'vol': '',
     'class_no': '598.1',
     'class_nm': '기술과학 > 가정학 및 가정생활 > 육아',
     'bookImageURL': 'https://image.aladin.co.kr/product/25313/30/cover/8934986654_1.jpg',
     'bookDtlUrl': 'https://data4library.kr/bookV?seq=5778286',
     'loan_count': '2085'}},
   {'doc': {'no': 19,
     'ranking': '19',
     'bookname': '흔한남매',
     'authors': '원작: 흔한남매 ;그림: 유난희',
     'publisher': '미래엔',
     'publication_year': '2019',
     'isbn13': '9791164132454',
     'addition_symbol': '77810',
     'vol': '2',
     'class_no': '810',
     'class_nm': '문학 > 한국문학 > 한국문학',
     'bookImageURL': 'https://image.aladin.co.kr/product/20398/4/cover/k002635150_1.jpg',
     'bookDtlUrl': 'https://data4library.kr/bookV?seq=5463101',
     'loan_count': '2073'}},
   {'doc': {'no': 20,
     'ranking': '20',
     'bookname': '흔한남매',
     'authors': '원작: 흔한남매 ;그림: 유난희',
     'publisher': '미래엔',
     'publication_year': '2019',
     'isbn13': '9791164134847',
     'addition_symbol': '77810',
     'vol': '4',
     'class_no': '810',
     'class_nm': '문학 > 한국문학 > 한국문학',
     'bookImageURL': 'https://image.aladin.co.kr/product/23568/96/cover/k992638123_1.jpg',
     'bookDtlUrl': 'https://data4library.kr/bookV?seq=5635121',
     'loan_count': '2069'}},
   {'doc': {'no': 21,
     'ranking': '21',
     'bookname': '(추리 천재) 엉덩이 탐정',
     'authors': '트롤 글·그림 ;김정화 옮김',
     'publisher': '미래엔',
     'publication_year': '2016',
     'isbn13': '9788937853470',
     'addition_symbol': '74830',
     'vol': '2',
     'class_no': '833.6',
     'class_nm': '문학 > 일본문학 > 소설',
     'bookImageURL': 'https://bookthumb-phinf.pstatic.net/cover/113/327/11332741.jpg?type=m1&udate=20161209',
     'bookDtlUrl': 'https://data4library.kr/bookV?seq=3392650',
     'loan_count': '2059'}},
   {'doc': {'no': 22,
     'ranking': '22',
     'bookname': '(이상한 과자 가게) 전천당',
     'authors': '히로시마 레이코 글 ;김정화 옮김',
     'publisher': '길벗스쿨',
     'publication_year': '2019',
     'isbn13': '9791164062270',
     'addition_symbol': '74830',
     'vol': '7',
     'class_no': '833.6',
     'class_nm': '문학 > 일본문학 > 소설',
     'bookImageURL': 'https://image.aladin.co.kr/product/24394/32/cover/k412630313_1.jpg',
     'bookDtlUrl': 'https://data4library.kr/bookV?seq=5699900',
     'loan_count': '2046'}},
   {'doc': {'no': 23,
     'ranking': '23',
     'bookname': '(이상한 과자 가게) 전천당',
     'authors': '히로시마 레이코 글 ;김정화 옮김',
     'publisher': '길벗스쿨',
     'publication_year': '2019',
     'isbn13': '9791164062065',
     'addition_symbol': '74830',
     'vol': '5',
     'class_no': '833.6',
     'class_nm': '문학 > 일본문학 > 소설',
     'bookImageURL': 'https://image.aladin.co.kr/product/23450/15/cover/k522638585_1.jpg',
     'bookDtlUrl': 'https://data4library.kr/bookV?seq=5609753',
     'loan_count': '2042'}},
   {'doc': {'no': 24,
     'ranking': '24',
     'bookname': '(추리 천재) 엉덩이 탐정',
     'authors': '트롤 글·그림 ;김정화 옮김',
     'publisher': '미래엔',
     'publication_year': '2016',
     'isbn13': '9788937838750',
     'addition_symbol': '74830',
     'vol': '1',
     'class_no': '833.6',
     'class_nm': '문학 > 일본문학 > 소설',
     'bookImageURL': 'http://image.aladin.co.kr/product/8920/23/cover/8937838753_1.jpg',
     'bookDtlUrl': 'https://data4library.kr/bookV?seq=3272507',
     'loan_count': '2039'}},
   {'doc': {'no': 25,
     'ranking': '25',
     'bookname': '(이상한 과자 가게) 전천당',
     'authors': '히로시마 레이코 글 ;김정화 옮김',
     'publisher': '길벗스쿨',
     'publication_year': '2019',
     'isbn13': '9791164060948',
     'addition_symbol': '74830',
     'vol': '4',
     'class_no': '833.6',
     'class_nm': '문학 > 일본문학 > 소설',
     'bookImageURL': 'https://image.aladin.co.kr/product/21439/72/cover/k272636199_1.jpg',
     'bookDtlUrl': 'https://data4library.kr/bookV?seq=5518313',
     'loan_count': '2036'}},
   {'doc': {'no': 26,
     'ranking': '26',
     'bookname': '(이상한 과자 가게) 전천당',
     'authors': '히로시마 레이코 글 ;김정화 옮김',
     'publisher': '길벗스쿨',
     'publication_year': '2019',
     'isbn13': '9791164062072',
     'addition_symbol': '74830',
     'vol': '6',
     'class_no': '833.6',
     'class_nm': '문학 > 일본문학 > 소설',
     'bookImageURL': 'https://image.aladin.co.kr/product/23450/17/cover/k692638585_1.jpg',
     'bookDtlUrl': 'https://data4library.kr/bookV?seq=5609754',
     'loan_count': '2018'}},
   {'doc': {'no': 27,
     'ranking': '27',
     'bookname': '(이상한 과자 가게) 전천당',
     'authors': '히로시마 레이코 글 ;김정화 옮김',
     'publisher': '길벗스쿨',
     'publication_year': '2019',
     'isbn13': '9791164062287',
     'addition_symbol': '74830',
     'vol': '8',
     'class_no': '833.6',
     'class_nm': '문학 > 일본문학 > 소설',
     'bookImageURL': 'https://image.aladin.co.kr/product/25020/81/cover/k782632928_1.jpg',
     'bookDtlUrl': 'https://data4library.kr/bookV?seq=5746636',
     'loan_count': '2008'}},
   {'doc': {'no': 28,
     'ranking': '28',
     'bookname': '(이상한 과자 가게) 전천당',
     'authors': '히로시마 레이코 글 ;김정화 옮김',
     'publisher': '길벗스쿨',
     'publication_year': '2019',
     'isbn13': '9791164062898',
     'addition_symbol': '74830',
     'vol': '9',
     'class_no': '833.6',
     'class_nm': '문학 > 일본문학 > 소설',
     'bookImageURL': 'https://image.aladin.co.kr/product/25732/47/cover/k092736875_1.jpg',
     'bookDtlUrl': 'https://data4library.kr/bookV?seq=5823468',
     'loan_count': '1988'}},
   {'doc': {'no': 29,
     'ranking': '29',
     'bookname': '나미야 잡화점의 기적 :히가시노 게이고 장편소설 ',
     'authors': '지은이: 히가시노 게이고 ;옮긴이: 양윤옥',
     'publisher': '현대문학',
     'publication_year': '2012',
     'isbn13': '9788972756194',
     'addition_symbol': '03830',
     'vol': '',
     'class_no': '833.6',
     'class_nm': '문학 > 일본문학 > 소설',
     'bookImageURL': 'http://image.aladin.co.kr/product/15848/6/cover/k622533431_1.jpg',
     'bookDtlUrl': 'https://data4library.kr/bookV?seq=1902173',
     'loan_count': '1987'}},
   {'doc': {'no': 30,
     'ranking': '30',
     'bookname': '흔한남매',
     'authors': '원작: 흔한남매 ;그림: 유난희',
     'publisher': '미래엔',
     'publication_year': '2019',
     'isbn13': '9791164136261',
     'addition_symbol': '77810',
     'vol': '6',
     'class_no': '810',
     'class_nm': '문학 > 한국문학 > 한국문학',
     'bookImageURL': 'https://image.aladin.co.kr/product/25301/95/cover/k062633309_1.jpg',
     'bookDtlUrl': 'https://data4library.kr/bookV?seq=5777315',
     'loan_count': '1946'}},
   {'doc': {'no': 31,
     'ranking': '31',
     'bookname': '수박 수영장 :안녕달 그림책 ',
     'authors': '지은이: 안녕달',
     'publisher': '창비',
     'publication_year': '2015',
     'isbn13': '9788936446819',
     'addition_symbol': '77810',
     'vol': '',
     'class_no': '813.7',
     'class_nm': '문학 > 한국문학 > 소설',
     'bookImageURL': 'https://bookthumb-phinf.pstatic.net/cover/093/451/09345174.jpg?type=m1&udate=20180718',
     'bookDtlUrl': 'https://data4library.kr/bookV?seq=2396971',
     'loan_count': '1911'}},
   {'doc': {'no': 32,
     'ranking': '32',
     'bookname': '우리가 빛의 속도로 갈 수 없다면 :김초엽 소설 ',
     'authors': '지은이: 김초엽',
     'publisher': '허블',
     'publication_year': '2019',
     'isbn13': '9791190090018',
     'addition_symbol': '03810',
     'vol': '',
     'class_no': '813.7',
     'class_nm': '문학 > 한국문학 > 소설',
     'bookImageURL': 'https://image.aladin.co.kr/product/19359/16/cover/s972635417_1.jpg',
     'bookDtlUrl': 'https://data4library.kr/bookV?seq=5430429',
     'loan_count': '1815'}},
   {'doc': {'no': 33,
     'ranking': '33',
     'bookname': '설민석의 한국사 대모험',
     'authors': '글: 설민석,그림: 정현희',
     'publisher': '휴먼큐브',
     'publication_year': '2017',
     'isbn13': '9791165382674',
     'addition_symbol': '74910',
     'vol': '14',
     'class_no': '911',
     'class_nm': '역사 > 아시아(아세아) > 한국',
     'bookImageURL': 'https://image.aladin.co.kr/product/24258/33/cover/k742630570_1.jpg',
     'bookDtlUrl': 'https://data4library.kr/bookV?seq=5686995',
     'loan_count': '1814'}},
   {'doc': {'no': 34,
     'ranking': '34',
     'bookname': '설민석의 한국사 대모험',
     'authors': '글: 설민석,그림: 정현희',
     'publisher': '휴먼큐브',
     'publication_year': '2017',
     'isbn13': '9791195794799',
     'addition_symbol': '74910',
     'vol': '1',
     'class_no': '911',
     'class_nm': '역사 > 아시아(아세아) > 한국',
     'bookImageURL': 'http://image.aladin.co.kr/product/10016/32/cover/k512536564_2.jpg',
     'bookDtlUrl': 'https://data4library.kr/bookV?seq=3405847',
     'loan_count': '1803'}},
   {'doc': {'no': 35,
     'ranking': '35',
     'bookname': '돈의 속성 :최상위 부자가 말하는 돈에 대한 모든 것 ',
     'authors': '지은이: 김승호',
     'publisher': 'Snowfox(스노우폭스북스)',
     'publication_year': '2020',
     'isbn13': '9791188331796',
     'addition_symbol': '03320',
     'vol': '',
     'class_no': '327.04',
     'class_nm': '사회과학 > 경제학 > 금융',
     'bookImageURL': 'https://image.aladin.co.kr/product/24191/64/cover/k562639753_1.jpg',
     'bookDtlUrl': 'https://data4library.kr/bookV?seq=5678862',
     'loan_count': '1783'}},
   {'doc': {'no': 36,
     'ranking': '36',
     'bookname': '당근 유치원 ',
     'authors': '지은이: 안녕달',
     'publisher': '창비',
     'publication_year': '2020',
     'isbn13': '9788936455484',
     'addition_symbol': '77810',
     'vol': '',
     'class_no': '813.7',
     'class_nm': '문학 > 한국문학 > 소설',
     'bookImageURL': 'https://image.aladin.co.kr/product/24011/82/cover/8936455486_1.jpg',
     'bookDtlUrl': 'https://data4library.kr/bookV?seq=5666934',
     'loan_count': '1781'}},
   {'doc': {'no': 37,
     'ranking': '37',
     'bookname': '어린이라는 세계 :김소영 에세이 ',
     'authors': '지은이: 김소영',
     'publisher': '사계절(사계절출판사)',
     'publication_year': '2020',
     'isbn13': '9791160946918',
     'addition_symbol': '03810',
     'vol': '',
     'class_no': '818',
     'class_nm': '문학 > 한국문학 > 르포르타주 및 기타',
     'bookImageURL': 'https://image.aladin.co.kr/product/25509/75/cover/k132633125_1.jpg',
     'bookDtlUrl': 'https://data4library.kr/bookV?seq=5795911',
     'loan_count': '1762'}},
   {'doc': {'no': 38,
     'ranking': '38',
     'bookname': '설민석의 한국사 대모험',
     'authors': '글: 설민석,그림: 정현희',
     'publisher': '휴먼큐브',
     'publication_year': '2017',
     'isbn13': '9791165382650',
     'addition_symbol': '74910',
     'vol': '13',
     'class_no': '911',
     'class_nm': '역사 > 아시아(아세아) > 한국',
     'bookImageURL': 'https://image.aladin.co.kr/product/23535/70/cover/k662638920_1.jpg',
     'bookDtlUrl': 'https://data4library.kr/bookV?seq=5623860',
     'loan_count': '1752'}},
   {'doc': {'no': 39,
     'ranking': '39',
     'bookname': '설민석의 한국사 대모험',
     'authors': '글: 설민석,그림: 정현희',
     'publisher': '휴먼큐브',
     'publication_year': '2017',
     'isbn13': '9791165382704',
     'addition_symbol': '74910',
     'vol': '15',
     'class_no': '911',
     'class_nm': '역사 > 아시아(아세아) > 한국',
     'bookImageURL': 'https://image.aladin.co.kr/product/25259/92/cover/k052633102_1.jpg',
     'bookDtlUrl': 'https://data4library.kr/bookV?seq=5776020',
     'loan_count': '1745'}},
   {'doc': {'no': 40,
     'ranking': '40',
     'bookname': '공정하다는 착각 :능력주의는 모두에게 같은 기회를 제공하는가 ',
     'authors': '마이클 샌델 지음 ;함규진 옮김',
     'publisher': '미래엔',
     'publication_year': '2020',
     'isbn13': '9791164136452',

In [ ]:
data = r.json() # requests.Response 객체의 json() method를 호출하면 json 문자열을 python 객체로 변환
print(data)

data # print() 함수로 출력하지 않아도 코드 셀의 마지막 라인의 실행 결과를 자동으로 출력

In [ ]:
books = []

# books = [d["doc"] for d in data["response"]["docs"]] 와 동일한 코드
for d in data["response"]["docs"] :
    books.append(d["doc"])

books

[{'no': 1,
  'ranking': '1',
  'bookname': '달러구트 꿈 백화점 :주문하신 꿈은 매진입니다 ',
  'authors': '지은이: 이미예',
  'publisher': '팩토리나인',
  'publication_year': '2020',
  'isbn13': '9791165341909',
  'addition_symbol': '03810',
  'vol': '',
  'class_no': '813.7',
  'class_nm': '문학 > 한국문학 > 소설',
  'bookImageURL': 'https://image.aladin.co.kr/product/24512/70/cover/k392630952_1.jpg',
  'bookDtlUrl': 'https://data4library.kr/bookV?seq=5707051',
  'loan_count': '2894'},
 {'no': 2,
  'ranking': '2',
  'bookname': '아몬드 :손원평 장편소설 ',
  'authors': '지은이: 손원평',
  'publisher': '창비',
  'publication_year': '2017',
  'isbn13': '9788936434267',
  'addition_symbol': '03810',
  'vol': '',
  'class_no': '813.7',
  'class_nm': '문학 > 한국문학 > 소설',
  'bookImageURL': 'http://image.aladin.co.kr/product/16839/4/cover/k492534773_1.jpg',
  'bookDtlUrl': 'https://data4library.kr/bookV?seq=3423096',
  'loan_count': '2841'},
 {'no': 3,
  'ranking': '3',
  'bookname': '(추리 천재) 엉덩이 탐정',
  'authors': '트롤 글·그림 ;김정화 옮김',
  'publisher': '미래엔',
  'publication_year': '2016',
  'isbn13': '9791164134090',
  'addition_symbol': '74830',
  'vol': '9',
  'class_no': '833.6',
  'class_nm': '문학 > 일본문학 > 소설',
  'bookImageURL': 'https://image.aladin.co.kr/product/22712/95/cover/k102636135_1.jpg',
  'bookDtlUrl': 'https://data4library.kr/bookV?seq=5581788',
  'loan_count': '2462'},
 {'no': 4,
  'ranking': '4',
  'bookname': '(추리 천재) 엉덩이 탐정',
  'authors': '트롤 글·그림 ;김정화 옮김',
  'publisher': '미래엔',
  'publication_year': '2016',
  'isbn13': '9791162339466',
  'addition_symbol': '74830',
  'vol': '7',
  'class_no': '833.6',
  'class_nm': '문학 > 일본문학 > 소설',
  'bookImageURL': 'https://image.aladin.co.kr/product/17457/14/cover/k792534209_1.jpg',
  'bookDtlUrl': 'https://data4library.kr/bookV?seq=5245643',
  'loan_count': '2355'},
 {'no': 5,
  'ranking': '5',
  'bookname': '(추리 천재) 엉덩이 탐정',
  'authors': '트롤 글·그림 ;김정화 옮김',
  'publisher': '미래엔',
  'publication_year': '2016',
  'isbn13': '9791164131914',
  'addition_symbol': '74830',
  'vol': '8',
  'class_no': '833.6',
  'class_nm': '문학 > 일본문학 > 소설',
  'bookImageURL': 'https://image.aladin.co.kr/product/19874/27/cover/k432635431_1.jpg',
  'bookDtlUrl': 'https://data4library.kr/bookV?seq=5448424',
  'loan_count': '2268'},
 {'no': 6,
  'ranking': '6',
  'bookname': '흔한남매',
  'authors': '원작: 흔한남매 ;그림: 유난희',
  'publisher': '미래엔',
  'publication_year': '2019',
  'isbn13': '9791164134267',
  'addition_symbol': '77810',
  'vol': '3',
  'class_no': '810',
  'class_nm': '문학 > 한국문학 > 한국문학',
  'bookImageURL': 'https://image.aladin.co.kr/product/22327/46/cover/k782636924_1.jpg',
  'bookDtlUrl': 'https://data4library.kr/bookV?seq=5569013',
  'loan_count': '2213'},
 {'no': 7,
  'ranking': '7',
  'bookname': '(추리 천재) 엉덩이 탐정',
  'authors': '트롤 글·그림 ;김정화 옮김',
  'publisher': '미래엔',
  'publication_year': '2016',
  'isbn13': '9791162332542',
  'addition_symbol': '74830',
  'vol': '5',
  'class_no': '833.6',
  'class_nm': '문학 > 일본문학 > 소설',
  'bookImageURL': 'https://bookthumb-phinf.pstatic.net/cover/129/756/12975600.jpg?type=m1&udate=20180126',
  'bookDtlUrl': 'https://data4library.kr/bookV?seq=3676788',
  'loan_count': '2202'},
 {'no': 8,
  'ranking': '8',
  'bookname': '시선으로부터, :정세랑 장편소설 ',
  'authors': '지은이: 정세랑',
  'publisher': '문학동네',
  'publication_year': '2020',
  'isbn13': '9788954672214',
  'addition_symbol': '03810',
  'vol': '',
  'class_no': '813.7',
  'class_nm': '문학 > 한국문학 > 소설',
  'bookImageURL': 'https://image.aladin.co.kr/product/24131/37/cover/8954672213_1.jpg',
  'bookDtlUrl': 'https://data4library.kr/bookV?seq=5674475',
  'loan_count': '2183'},
 {'no': 9,
  'ranking': '9',
  'bookname': '(이상한 과자 가게) 전천당',
  'authors': '히로시마 레이코 글 ;김정화 옮김',
  'publisher': '길벗스쿨',
  'publication_year': '2019',
  'isbn13': '9791164060481',
  'addition_symbol': '74830',
  'vol': '1',
  'class_no': '833.6',
  'class_nm': '문학 > 일본문학 > 소설',
  'bookImageURL': 'https://image.aladin.co.kr/product/19610/47/cover/k282635522_1.jpg',
  'bookDtlUrl': 'https://data4library.kr/bookV?seq=5439175',
  'loan_count': '2180'},
 {'no': 10,
  'ranking': '10',
  'bookname': '(추리 천재) 엉덩이 탐정',
  'authors': '트롤 글·그림 ;김정화 옮김',
  'publisher': '미래엔',
  'publication_year': '2016',
  'isbn13': '9788937848247',
  'addition_symbol': '74830',
  'vol': '4',
  'class_no': '833.6',
  'class_nm': '문학 > 일본문학 > 소설',
  'bookImageURL': 'https://bookthumb-phinf.pstatic.net/cover/124/953/12495377.jpg?type=m1&udate=20170829',
  'bookDtlUrl': 'https://data4library.kr/bookV?seq=3541426',
  'loan_count': '2168'},
 {'no': 11,
  'ranking': '11',
  'bookname': '(추리 천재) 엉덩이 탐정',
  'authors': '트롤 글·그림 ;김정화 옮김',
  'publisher': '미래엔',
  'publication_year': '2016',
  'isbn13': '9791162335123',
  'addition_symbol': '74830',
  'vol': '6',
  'class_no': '833.6',
  'class_nm': '문학 > 일본문학 > 소설',
  'bookImageURL': 'https://bookthumb-phinf.pstatic.net/cover/135/613/13561388.jpg?type=m1&udate=20180619',
  'bookDtlUrl': 'https://data4library.kr/bookV?seq=3746485',
  'loan_count': '2160'},
 {'no': 12,
  'ranking': '12',
  'bookname': '(추리 천재) 엉덩이 탐정',
  'authors': '트롤 글·그림 ;김정화 옮김',
  'publisher': '미래엔',
  'publication_year': '2016',
  'isbn13': '9791164137053',
  'addition_symbol': '74830',
  'vol': '10',
  'class_no': '833.6',
  'class_nm': '문학 > 일본문학 > 소설',
  'bookImageURL': 'https://image.aladin.co.kr/product/25801/42/cover/k252736232_1.jpg',
  'bookDtlUrl': 'https://data4library.kr/bookV?seq=5827187',
  'loan_count': '2152'},
 {'no': 13,
  'ranking': '13',
  'bookname': '(추리 천재) 엉덩이 탐정',
  'authors': '트롤 글·그림 ;김정화 옮김',
  'publisher': '미래엔',
  'publication_year': '2016',
  'isbn13': '9788937889714',
  'addition_symbol': '74830',
  'vol': '3',
  'class_no': '833.6',
  'class_nm': '문학 > 일본문학 > 소설',
  'bookImageURL': 'http://image.aladin.co.kr/product/10644/93/cover/8937889714_1.jpg',
  'bookDtlUrl': 'https://data4library.kr/bookV?seq=3425818',
  'loan_count': '2127'},
 {'no': 14,
  'ranking': '14',
  'bookname': '흔한남매',
  'authors': '원작: 흔한남매 ;그림: 유난희',
  'publisher': '미래엔',
  'publication_year': '2019',
  'isbn13': '9791164135592',
  'addition_symbol': '77810',
  'vol': '5',
  'class_no': '810',
  'class_nm': '문학 > 한국문학 > 한국문학',
  'bookImageURL': 'https://image.aladin.co.kr/product/24307/73/cover/k822630592_2.jpg',
  'bookDtlUrl': 'https://data4library.kr/bookV?seq=5686627',
  'loan_count': '2125'},
 {'no': 15,
  'ranking': '15',
  'bookname': '흔한남매',
  'authors': '원작: 흔한남매 ;그림: 유난희',
  'publisher': '미래엔',
  'publication_year': '2019',
  'isbn13': '9791164131686',
  'addition_symbol': '77810',
  'vol': '1',
  'class_no': '810',
  'class_nm': '문학 > 한국문학 > 한국문학',
  'bookImageURL': 'https://image.aladin.co.kr/product/19404/61/cover/k712635217_1.jpg',
  'bookDtlUrl': 'https://data4library.kr/bookV?seq=5429011',
  'loan_count': '2115'},
 {'no': 16,
  'ranking': '16',
  'bookname': '(이상한 과자 가게) 전천당',
  'authors': '히로시마 레이코 글 ;김정화 옮김',
  'publisher': '길벗스쿨',
  'publication_year': '2019',
  'isbn13': '9791164060498',
  'addition_symbol': '74830',
  'vol': '2',
  'class_no': '833.6',
  'class_nm': '문학 > 일본문학 > 소설',
  'bookImageURL': 'https://image.aladin.co.kr/product/19612/74/cover/k772635522_1.jpg',
  'bookDtlUrl': 'https://data4library.kr/bookV?seq=5439173',
  'loan_count': '2101'},
 {'no': 17,
  'ranking': '17',
  'bookname': '(이상한 과자 가게) 전천당',
  'authors': '히로시마 레이코 글 ;김정화 옮김',
  'publisher': '길벗스쿨',
  'publication_year': '2019',
  'isbn13': '9791164060931',
  'addition_symbol': '74830',
  'vol': '3',
  'class_no': '833.6',
  'class_nm': '문학 > 일본문학 > 소설',
  'bookImageURL': 'https://image.aladin.co.kr/product/21439/64/cover/k142636199_1.jpg',
  'bookDtlUrl': 'https://data4library.kr/bookV?seq=5518312',
  'loan_count': '2086'},
 {'no': 18,
  'ranking': '18',
  'bookname': '어떻게 말해줘야 할까 :오은영의 현실밀착 육아회화 ',
  'authors': '글: 오은영 ;그림: 차상미',
  'publisher': '김영사',
  'publication_year': '2020',
  'isbn13': '9788934986652',
  'addition_symbol': '13590',
  'vol': '',
  'class_no': '598.1',
  'class_nm': '기술과학 > 가정학 및 가정생활 > 육아',
  'bookImageURL': 'https://image.aladin.co.kr/product/25313/30/cover/8934986654_1.jpg',
  'bookDtlUrl': 'https://data4library.kr/bookV?seq=5778286',
  'loan_count': '2085'},
 {'no': 19,
  'ranking': '19',
  'bookname': '흔한남매',
  'authors': '원작: 흔한남매 ;그림: 유난희',
  'publisher': '미래엔',
  'publication_year': '2019',
  'isbn13': '9791164132454',
  'addition_symbol': '77810',
  'vol': '2',
  'class_no': '810',
  'class_nm': '문학 > 한국문학 > 한국문학',
  'bookImageURL': 'https://image.aladin.co.kr/product/20398/4/cover/k002635150_1.jpg',
  'bookDtlUrl': 'https://data4library.kr/bookV?seq=5463101',
  'loan_count': '2073'},
 {'no': 20,
  'ranking': '20',
  'bookname': '흔한남매',
  'authors': '원작: 흔한남매 ;그림: 유난희',
  'publisher': '미래엔',
  'publication_year': '2019',
  'isbn13': '9791164134847',
  'addition_symbol': '77810',
  'vol': '4',
  'class_no': '810',
  'class_nm': '문학 > 한국문학 > 한국문학',
  'bookImageURL': 'https://image.aladin.co.kr/product/23568/96/cover/k992638123_1.jpg',
  'bookDtlUrl': 'https://data4library.kr/bookV?seq=5635121',
  'loan_count': '2069'},
 {'no': 21,
  'ranking': '21',
  'bookname': '(추리 천재) 엉덩이 탐정',
  'authors': '트롤 글·그림 ;김정화 옮김',
  'publisher': '미래엔',
  'publication_year': '2016',
  'isbn13': '9788937853470',
  'addition_symbol': '74830',
  'vol': '2',
  'class_no': '833.6',
  'class_nm': '문학 > 일본문학 > 소설',
  'bookImageURL': 'https://bookthumb-phinf.pstatic.net/cover/113/327/11332741.jpg?type=m1&udate=20161209',
  'bookDtlUrl': 'https://data4library.kr/bookV?seq=3392650',
  'loan_count': '2059'},
 {'no': 22,
  'ranking': '22',
  'bookname': '(이상한 과자 가게) 전천당',
  'authors': '히로시마 레이코 글 ;김정화 옮김',
  'publisher': '길벗스쿨',
  'publication_year': '2019',
  'isbn13': '9791164062270',
  'addition_symbol': '74830',
  'vol': '7',
  'class_no': '833.6',
  'class_nm': '문학 > 일본문학 > 소설',
  'bookImageURL': 'https://image.aladin.co.kr/product/24394/32/cover/k412630313_1.jpg',
  'bookDtlUrl': 'https://data4library.kr/bookV?seq=5699900',
  'loan_count': '2046'},
 {'no': 23,
  'ranking': '23',
  'bookname': '(이상한 과자 가게) 전천당',
  'authors': '히로시마 레이코 글 ;김정화 옮김',
  'publisher': '길벗스쿨',
  'publication_year': '2019',
  'isbn13': '9791164062065',
  'addition_symbol': '74830',
  'vol': '5',
  'class_no': '833.6',
  'class_nm': '문학 > 일본문학 > 소설',
  'bookImageURL': 'https://image.aladin.co.kr/product/23450/15/cover/k522638585_1.jpg',
  'bookDtlUrl': 'https://data4library.kr/bookV?seq=5609753',
  'loan_count': '2042'},
 {'no': 24,
  'ranking': '24',
  'bookname': '(추리 천재) 엉덩이 탐정',
  'authors': '트롤 글·그림 ;김정화 옮김',
  'publisher': '미래엔',
  'publication_year': '2016',
  'isbn13': '9788937838750',
  'addition_symbol': '74830',
  'vol': '1',
  'class_no': '833.6',
  'class_nm': '문학 > 일본문학 > 소설',
  'bookImageURL': 'http://image.aladin.co.kr/product/8920/23/cover/8937838753_1.jpg',
  'bookDtlUrl': 'https://data4library.kr/bookV?seq=3272507',
  'loan_count': '2039'},
 {'no': 25,
  'ranking': '25',
  'bookname': '(이상한 과자 가게) 전천당',
  'authors': '히로시마 레이코 글 ;김정화 옮김',
  'publisher': '길벗스쿨',
  'publication_year': '2019',
  'isbn13': '9791164060948',
  'addition_symbol': '74830',
  'vol': '4',
  'class_no': '833.6',
  'class_nm': '문학 > 일본문학 > 소설',
  'bookImageURL': 'https://image.aladin.co.kr/product/21439/72/cover/k272636199_1.jpg',
  'bookDtlUrl': 'https://data4library.kr/bookV?seq=5518313',
  'loan_count': '2036'},
 {'no': 26,
  'ranking': '26',
  'bookname': '(이상한 과자 가게) 전천당',
  'authors': '히로시마 레이코 글 ;김정화 옮김',
  'publisher': '길벗스쿨',
  'publication_year': '2019',
  'isbn13': '9791164062072',
  'addition_symbol': '74830',
  'vol': '6',
  'class_no': '833.6',
  'class_nm': '문학 > 일본문학 > 소설',
  'bookImageURL': 'https://image.aladin.co.kr/product/23450/17/cover/k692638585_1.jpg',
  'bookDtlUrl': 'https://data4library.kr/bookV?seq=5609754',
  'loan_count': '2018'},
 {'no': 27,
  'ranking': '27',
  'bookname': '(이상한 과자 가게) 전천당',
  'authors': '히로시마 레이코 글 ;김정화 옮김',
  'publisher': '길벗스쿨',
  'publication_year': '2019',
  'isbn13': '9791164062287',
  'addition_symbol': '74830',
  'vol': '8',
  'class_no': '833.6',
  'class_nm': '문학 > 일본문학 > 소설',
  'bookImageURL': 'https://image.aladin.co.kr/product/25020/81/cover/k782632928_1.jpg',
  'bookDtlUrl': 'https://data4library.kr/bookV?seq=5746636',
  'loan_count': '2008'},
 {'no': 28,
  'ranking': '28',
  'bookname': '(이상한 과자 가게) 전천당',
  'authors': '히로시마 레이코 글 ;김정화 옮김',
  'publisher': '길벗스쿨',
  'publication_year': '2019',
  'isbn13': '9791164062898',
  'addition_symbol': '74830',
  'vol': '9',
  'class_no': '833.6',
  'class_nm': '문학 > 일본문학 > 소설',
  'bookImageURL': 'https://image.aladin.co.kr/product/25732/47/cover/k092736875_1.jpg',
  'bookDtlUrl': 'https://data4library.kr/bookV?seq=5823468',
  'loan_count': '1988'},
 {'no': 29,
  'ranking': '29',
  'bookname': '나미야 잡화점의 기적 :히가시노 게이고 장편소설 ',
  'authors': '지은이: 히가시노 게이고 ;옮긴이: 양윤옥',
  'publisher': '현대문학',
  'publication_year': '2012',
  'isbn13': '9788972756194',
  'addition_symbol': '03830',
  'vol': '',
  'class_no': '833.6',
  'class_nm': '문학 > 일본문학 > 소설',
  'bookImageURL': 'http://image.aladin.co.kr/product/15848/6/cover/k622533431_1.jpg',
  'bookDtlUrl': 'https://data4library.kr/bookV?seq=1902173',
  'loan_count': '1987'},
 {'no': 30,
  'ranking': '30',
  'bookname': '흔한남매',
  'authors': '원작: 흔한남매 ;그림: 유난희',
  'publisher': '미래엔',
  'publication_year': '2019',
  'isbn13': '9791164136261',
  'addition_symbol': '77810',
  'vol': '6',
  'class_no': '810',
  'class_nm': '문학 > 한국문학 > 한국문학',
  'bookImageURL': 'https://image.aladin.co.kr/product/25301/95/cover/k062633309_1.jpg',
  'bookDtlUrl': 'https://data4library.kr/bookV?seq=5777315',
  'loan_count': '1946'},
 {'no': 31,
  'ranking': '31',
  'bookname': '수박 수영장 :안녕달 그림책 ',
  'authors': '지은이: 안녕달',
  'publisher': '창비',
  'publication_year': '2015',
  'isbn13': '9788936446819',
  'addition_symbol': '77810',
  'vol': '',
  'class_no': '813.7',
  'class_nm': '문학 > 한국문학 > 소설',
  'bookImageURL': 'https://bookthumb-phinf.pstatic.net/cover/093/451/09345174.jpg?type=m1&udate=20180718',
  'bookDtlUrl': 'https://data4library.kr/bookV?seq=2396971',
  'loan_count': '1911'},
 {'no': 32,
  'ranking': '32',
  'bookname': '우리가 빛의 속도로 갈 수 없다면 :김초엽 소설 ',
  'authors': '지은이: 김초엽',
  'publisher': '허블',
  'publication_year': '2019',
  'isbn13': '9791190090018',
  'addition_symbol': '03810',
  'vol': '',
  'class_no': '813.7',
  'class_nm': '문학 > 한국문학 > 소설',
  'bookImageURL': 'https://image.aladin.co.kr/product/19359/16/cover/s972635417_1.jpg',
  'bookDtlUrl': 'https://data4library.kr/bookV?seq=5430429',
  'loan_count': '1815'},
 {'no': 33,
  'ranking': '33',
  'bookname': '설민석의 한국사 대모험',
  'authors': '글: 설민석,그림: 정현희',
  'publisher': '휴먼큐브',
  'publication_year': '2017',
  'isbn13': '9791165382674',
  'addition_symbol': '74910',
  'vol': '14',
  'class_no': '911',
  'class_nm': '역사 > 아시아(아세아) > 한국',
  'bookImageURL': 'https://image.aladin.co.kr/product/24258/33/cover/k742630570_1.jpg',
  'bookDtlUrl': 'https://data4library.kr/bookV?seq=5686995',
  'loan_count': '1814'},
 {'no': 34,
  'ranking': '34',
  'bookname': '설민석의 한국사 대모험',
  'authors': '글: 설민석,그림: 정현희',
  'publisher': '휴먼큐브',
  'publication_year': '2017',
  'isbn13': '9791195794799',
  'addition_symbol': '74910',
  'vol': '1',
  'class_no': '911',
  'class_nm': '역사 > 아시아(아세아) > 한국',
  'bookImageURL': 'http://image.aladin.co.kr/product/10016/32/cover/k512536564_2.jpg',
  'bookDtlUrl': 'https://data4library.kr/bookV?seq=3405847',
  'loan_count': '1803'},
 {'no': 35,
  'ranking': '35',
  'bookname': '돈의 속성 :최상위 부자가 말하는 돈에 대한 모든 것 ',
  'authors': '지은이: 김승호',
  'publisher': 'Snowfox(스노우폭스북스)',
  'publication_year': '2020',
  'isbn13': '9791188331796',
  'addition_symbol': '03320',
  'vol': '',
  'class_no': '327.04',
  'class_nm': '사회과학 > 경제학 > 금융',
  'bookImageURL': 'https://image.aladin.co.kr/product/24191/64/cover/k562639753_1.jpg',
  'bookDtlUrl': 'https://data4library.kr/bookV?seq=5678862',
  'loan_count': '1783'},
 {'no': 36,
  'ranking': '36',
  'bookname': '당근 유치원 ',
  'authors': '지은이: 안녕달',
  'publisher': '창비',
  'publication_year': '2020',
  'isbn13': '9788936455484',
  'addition_symbol': '77810',
  'vol': '',
  'class_no': '813.7',
  'class_nm': '문학 > 한국문학 > 소설',
  'bookImageURL': 'https://image.aladin.co.kr/product/24011/82/cover/8936455486_1.jpg',
  'bookDtlUrl': 'https://data4library.kr/bookV?seq=5666934',
  'loan_count': '1781'},
 {'no': 37,
  'ranking': '37',
  'bookname': '어린이라는 세계 :김소영 에세이 ',
  'authors': '지은이: 김소영',
  'publisher': '사계절(사계절출판사)',
  'publication_year': '2020',
  'isbn13': '9791160946918',
  'addition_symbol': '03810',
  'vol': '',
  'class_no': '818',
  'class_nm': '문학 > 한국문학 > 르포르타주 및 기타',
  'bookImageURL': 'https://image.aladin.co.kr/product/25509/75/cover/k132633125_1.jpg',
  'bookDtlUrl': 'https://data4library.kr/bookV?seq=5795911',
  'loan_count': '1762'},
 {'no': 38,
  'ranking': '38',
  'bookname': '설민석의 한국사 대모험',
  'authors': '글: 설민석,그림: 정현희',
  'publisher': '휴먼큐브',
  'publication_year': '2017',
  'isbn13': '9791165382650',
  'addition_symbol': '74910',
  'vol': '13',
  'class_no': '911',
  'class_nm': '역사 > 아시아(아세아) > 한국',
  'bookImageURL': 'https://image.aladin.co.kr/product/23535/70/cover/k662638920_1.jpg',
  'bookDtlUrl': 'https://data4library.kr/bookV?seq=5623860',
  'loan_count': '1752'},
 {'no': 39,
  'ranking': '39',
  'bookname': '설민석의 한국사 대모험',
  'authors': '글: 설민석,그림: 정현희',
  'publisher': '휴먼큐브',
  'publication_year': '2017',
  'isbn13': '9791165382704',
  'addition_symbol': '74910',
  'vol': '15',
  'class_no': '911',
  'class_nm': '역사 > 아시아(아세아) > 한국',
  'bookImageURL': 'https://image.aladin.co.kr/product/25259/92/cover/k052633102_1.jpg',
  'bookDtlUrl': 'https://data4library.kr/bookV?seq=5776020',
  'loan_count': '1745'},
 {'no': 40,
  'ranking': '40',
  'bookname': '공정하다는 착각 :능력주의는 모두에게 같은 기회를 제공하는가 ',
  'authors': '마이클 샌델 지음 ;함규진 옮김',
  'publisher': '미래엔',
  'publication_year': '2020',
  'isbn13': '9791164136452',
  'addition_symbol': '03300',
  'vol': '',
  'class_no': '332.6',
  'class_nm': '사회과학 > 사회학, 사회문제 > 사회조직 및 제도',
  'bookImageURL': 'https://image.aladin.co.kr/product/25470/6/cover/k092633826_1.jpg',
  'bookDtlUrl': 'https://data4library.kr/bookV?seq=5791228',
  'loan_count': '1740'},
 {'no': 41,
  'ranking': '41',
  'bookname': '나의 하루는 4시 30분에 시작된다 :하루를 두 배로 사는 단 하나의 습관 ',
  'authors': '김유진 지음',
  'publisher': 'Tornado(토네이도)',
  'publication_year': '2020',
  'isbn13': '9791158511906',
  'addition_symbol': '03190',
  'vol': '',
  'class_no': '325.211',
  'class_nm': '사회과학 > 경제학 > 경영관리',
  'bookImageURL': 'https://image.aladin.co.kr/product/25306/49/cover/k922633306_1.jpg',
  'bookDtlUrl': 'https://data4library.kr/bookV?seq=5778871',
  'loan_count': '1703'},
 {'no': 42,
  'ranking': '42',
  'bookname': '파친코 :이민진 장편소설',
  'authors': '이민진 지음 ;이미정 옮김',
  'publisher': '문학사상',
  'publication_year': '2018',
  'isbn13': '9788970129815',
  'addition_symbol': '04840',
  'vol': '1',
  'class_no': '843.6',
  'class_nm': '문학 > 영미문학 > 소설',
  'bookImageURL': 'https://bookthumb-phinf.pstatic.net/cover/134/282/13428208.jpg?type=m1&udate=20180331',
  'bookDtlUrl': 'https://data4library.kr/bookV?seq=3723218',
  'loan_count': '1701'},
 {'no': 43,
  'ranking': '43',
  'bookname': '설민석의 한국사 대모험',
  'authors': '글: 설민석,그림: 정현희',
  'publisher': '휴먼큐브',
  'publication_year': '2017',
  'isbn13': '9791188874460',
  'addition_symbol': '74910',
  'vol': '12',
  'class_no': '911',
  'class_nm': '역사 > 아시아(아세아) > 한국',
  'bookImageURL': 'https://image.aladin.co.kr/product/21613/51/cover/k122636592_1.jpg',
  'bookDtlUrl': 'https://data4library.kr/bookV?seq=5521219',
  'loan_count': '1700'},
 {'no': 44,
  'ranking': '44',
  'bookname': '아홉 살 마음 사전 ',
  'authors': '박성우 글 ;김효은 그림',
  'publisher': '창비',
  'publication_year': '2017',
  'isbn13': '9788936447014',
  'addition_symbol': '73710',
  'vol': '',
  'class_no': '181',
  'class_nm': '철학 > 심리학 > 각론',
  'bookImageURL': 'http://image.aladin.co.kr/product/10537/49/cover/8936447017_1.jpg',
  'bookDtlUrl': 'https://data4library.kr/bookV?seq=3421838',
  'loan_count': '1696'},
 {'no': 45,
  'ranking': '45',

In [19]:
# 도서 정보가 담긴 dictionary의 list를 데이터프레임으로 변환
books_df = pd.DataFrame(books)
books_df

,no,ranking,bookname,authors,publisher,publication_year,isbn13,addition_symbol,vol,class_no,class_nm,bookImageURL,bookDtlUrl,loan_count
0,1,1,달러구트 꿈 백화점 :주문하신 꿈은 매진입니다,지은이: 이미예,팩토리나인,2020,9791165341909,03810,,813.7,문학 > 한국문학 > 소설,https://image.aladin.co.kr/product/24512/70/co...,https://data4library.kr/bookV?seq=5707051,2894
1,2,2,아몬드 :손원평 장편소설,지은이: 손원평,창비,2017,9788936434267,03810,,813.7,문학 > 한국문학 > 소설,http://image.aladin.co.kr/product/16839/4/cove...,https://data4library.kr/bookV?seq=3423096,2841
2,3,3,(추리 천재) 엉덩이 탐정,트롤 글·그림 ;김정화 옮김,미래엔,2016,9791164134090,74830,9,833.6,문학 > 일본문학 > 소설,https://image.aladin.co.kr/product/22712/95/co...,https://data4library.kr/bookV?seq=5581788,2462
3,4,4,(추리 천재) 엉덩이 탐정,트롤 글·그림 ;김정화 옮김,미래엔,2016,9791162339466,74830,7,833.6,문학 > 일본문학 > 소설,https://image.aladin.co.kr/product/17457/14/co...,https://data4library.kr/bookV?seq=5245643,2355
4,5,5,(추리 천재) 엉덩이 탐정,트롤 글·그림 ;김정화 옮김,미래엔,2016,9791164131914,74830,8,833.6,문학 > 일본문학 > 소설,https://image.aladin.co.kr/product/19874/27/co...,https://data4library.kr/bookV?seq=5448424,2268
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,196,196,117층 나무 집,앤디 그리피스 글 ;신수진 옮김,시공사,2020,9788952744586,74840,,843,문학 > 영미문학 > 소설,https://image.aladin.co.kr/product/22210/28/co...,https://data4library.kr/bookV?seq=5548964,1089
196,197,196,수학 잘하는 아이는 이렇게 공부합니다 :수학이 어려운 엄마를 위한 전략적 학습 로드맵,류승재 지음,블루무스,2021,9791196848194,03370,,410.7,자연과학 > 수학 > 수학,https://image.aladin.co.kr/product/26294/23/co...,https://data4library.kr/bookV?seq=5856565,1089
197,198,198,나는 개다,백희나,책읽는곰,2019,9791158361365,77810,,813.7,문학 > 한국문학 > 소설,https://image.aladin.co.kr/product/18827/90/co...,https://data4library.kr/bookV?seq=5390730,1084
198,199,198,부의 대이동 :달러와 금의 흐름으로 읽는 미래 투자 전략,오건영 지음,Page2(페이지2북스),2020,9791196831080,03320,,327.8,사회과학 > 경제학 > 금융,https://image.aladin.co.kr/product/24607/53/co...,https://data4library.kr/bookV?seq=5708822,1084
199,200,200,놓지 마 과학!,"글·그림: 신태훈,나승훈",위즈덤하우스,2016,9791190908184,67400,14,408,"자연과학 > 자연과학 > 전집, 총서",https://image.aladin.co.kr/product/24628/1/cov...,https://data4library.kr/bookV?seq=5709267,1083

In [20]:
# 데이터프레임을 json으로 변환
books_df.to_json("20_best_book.json")