#

# 2가지 키워드로 정리하는 핵심 포인트
* 웹 스크래핑
    * 웹사이트에서 필요한 데이터를 추출하는 기술
    * HTML은 구조적이지 않기 때문에 스크래핑으로 데이터를 수집하는데 비교적 많은 노력 필요
    * 웹 스크래핑을 사용하기 전에 먼저 공개 API를 통해 사용할 수 있는지 확인하는 것이 좋음
* 뷰티플수프
    * HTML문서를 파싱하는데 사용하는 대표적인 python 패키지
    * 사용법이 쉽고 빠름
    * requests 패키지로 가져온 HTML에서 원하는 tag나 text를 찾는 기능 제공

# 핵심 함수와 매서드
* `loc`
    * 레이블(이름) 또는 boolean 배열로 데이터프레임의 행과 열을 선택
    * 정수로 지정하면 index의 레이블로 간주
    * boolean 배열로 지정할 경우 배열의 길이는 행 또는 열의 전체 길이와 같아야 함
* `BeautifulSoup.find()`
    * 현재 tag 아래의 자식 tag 중에서 지정된 이름에 맞는 첫 번째 tag를 찾음
    * 찾은 tag가 없을 경우 None 반환
* `BeautifulSoup.find_all()`
    * 현재 tag 아래의 자식 tag 중에서 지정된 이름에 맞는 모든 tag를 찾음
    * BeautifulSoup 객체를 함수처럼 호출할 경우 자동으로 find_all() method가 호출됨
    * 찾은 tag가 없을 경우 빈 list 반환
* `BeautifulSoup.get_text()`
    * tag 안의 text를 반환
* `DataFrame.apply()`
    * 데이터프레임의 행 또는 열에 지정한 함수 적용
* `pandas.merge()`
    * 데이터프레임이나 시리즈 객체를 병합

목표 : 02_1에서 생성한 도서의 쪽수를 웹 스크래핑(web scraping 혹은 웹 크롤링(web crawling))으로 가져오기

In [74]:
# 저장된 파일을 web에서 가져오는 방법
import gdown

gdown.download("https://bit.ly/3q9SZix", '20s_best_book_web.json', quiet=False)

Downloading...
From: https://bit.ly/3q9SZix
To: d:\github\TIL\데이터분석\02\20s_best_book_web.json
100%|██████████| 92.9k/92.9k [00:00<00:00, 1.07MB/s]

'20s_best_book_web.json'

In [75]:
# local에 저장된 파일을 가져오는 방법 -> 경로를 넣어주면 됨
import pandas as pd

books_df = pd.read_json("20_best_book.json")

# web에서 불러온 파일을 사용하려면
# books_df = pd.read_json("20s_best_book_web.json")

books_df.head()

,no,ranking,bookname,authors,publisher,publication_year,isbn13,addition_symbol,vol,class_no,class_nm,bookImageURL,bookDtlUrl,loan_count
0,1,1,달러구트 꿈 백화점 :주문하신 꿈은 매진입니다,지은이: 이미예,팩토리나인,2020,9791165341909,3810,,813.7,문학 > 한국문학 > 소설,https://image.aladin.co.kr/product/24512/70/co...,https://data4library.kr/bookV?seq=5707051,2894
1,2,2,아몬드 :손원평 장편소설,지은이: 손원평,창비,2017,9788936434267,3810,,813.7,문학 > 한국문학 > 소설,http://image.aladin.co.kr/product/16839/4/cove...,https://data4library.kr/bookV?seq=3423096,2841
2,3,3,(추리 천재) 엉덩이 탐정,트롤 글·그림 ;김정화 옮김,미래엔,2016,9791164134090,74830,9,833.6,문학 > 일본문학 > 소설,https://image.aladin.co.kr/product/22712/95/co...,https://data4library.kr/bookV?seq=5581788,2462
3,4,4,(추리 천재) 엉덩이 탐정,트롤 글·그림 ;김정화 옮김,미래엔,2016,9791162339466,74830,7,833.6,문학 > 일본문학 > 소설,https://image.aladin.co.kr/product/17457/14/co...,https://data4library.kr/bookV?seq=5245643,2355
4,5,5,(추리 천재) 엉덩이 탐정,트롤 글·그림 ;김정화 옮김,미래엔,2016,9791164131914,74830,8,833.6,문학 > 일본문학 > 소설,https://image.aladin.co.kr/product/19874/27/co...,https://data4library.kr/bookV?seq=5448424,2268

In [76]:
# 데이터 프레임의 열이 너무 많으므로 특정열까지만 선택하여 새로운 데이터프레임 생성
books = books_df[["no", "ranking", "bookname", "authors", "publisher", "publication_year", "isbn13"]]
books.head()

,no,ranking,bookname,authors,publisher,publication_year,isbn13
0,1,1,달러구트 꿈 백화점 :주문하신 꿈은 매진입니다,지은이: 이미예,팩토리나인,2020,9791165341909
1,2,2,아몬드 :손원평 장편소설,지은이: 손원평,창비,2017,9788936434267
2,3,3,(추리 천재) 엉덩이 탐정,트롤 글·그림 ;김정화 옮김,미래엔,2016,9791164134090
3,4,4,(추리 천재) 엉덩이 탐정,트롤 글·그림 ;김정화 옮김,미래엔,2016,9791162339466
4,5,5,(추리 천재) 엉덩이 탐정,트롤 글·그림 ;김정화 옮김,미래엔,2016,9791164131914

In [77]:
# loc() : 원하는 행과 열을 선택하는 method
books_df.loc[[0, 1], ["bookname", "authors", "publisher"]]

# loc() method는 list 대신 슬라이스 연산자(:) 사용 가능 (위 code와 동일한 code)
books_df.loc[0:1, "bookname":"publisher"]

# 주의할 점은 python의 슬라이싱과 다르게 마지막 항목도 포함됨!!

                     bookname   authors publisher
0  달러구트 꿈 백화점 :주문하신 꿈은 매진입니다   지은이: 이미예     팩토리나인
1              아몬드 :손원평 장편소설   지은이: 손원평        창비

In [78]:
# 시작과 끝을 지정하지 않고 슬라이스 연산자를 사용하면 전체를 의미
books = books_df.loc[:, "no":"isbn13"]
books.head()

,no,ranking,bookname,authors,publisher,publication_year,isbn13
0,1,1,달러구트 꿈 백화점 :주문하신 꿈은 매진입니다,지은이: 이미예,팩토리나인,2020,9791165341909
1,2,2,아몬드 :손원평 장편소설,지은이: 손원평,창비,2017,9788936434267
2,3,3,(추리 천재) 엉덩이 탐정,트롤 글·그림 ;김정화 옮김,미래엔,2016,9791164134090
3,4,4,(추리 천재) 엉덩이 탐정,트롤 글·그림 ;김정화 옮김,미래엔,2016,9791162339466
4,5,5,(추리 천재) 엉덩이 탐정,트롤 글·그림 ;김정화 옮김,미래엔,2016,9791164131914

In [79]:
# python 슬라이싱처럼 step도 지정 가능
books_df.loc[::2, "no":"isbn13"].head()

,no,ranking,bookname,authors,publisher,publication_year,isbn13
0,1,1,달러구트 꿈 백화점 :주문하신 꿈은 매진입니다,지은이: 이미예,팩토리나인,2020,9791165341909
2,3,3,(추리 천재) 엉덩이 탐정,트롤 글·그림 ;김정화 옮김,미래엔,2016,9791164134090
4,5,5,(추리 천재) 엉덩이 탐정,트롤 글·그림 ;김정화 옮김,미래엔,2016,9791164131914
6,7,7,(추리 천재) 엉덩이 탐정,트롤 글·그림 ;김정화 옮김,미래엔,2016,9791162332542
8,9,9,(이상한 과자 가게) 전천당,히로시마 레이코 글 ;김정화 옮김,길벗스쿨,2019,9791164060481

In [80]:
import requests

isbn = 9791165341909
url = 'http://www.yes24.com/Product/Search?domain=BOOK&query={}'
r = requests.get(url.format(isbn))

print(r.text) # 도서 검색 결과 페이지 HTML을 출력

<!DOCTYPE html>
<html lang="ko">
<head>
        <meta http-equiv="X-UA-Compatible" content="IE=Edge" />
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
    <meta http-equiv="Accept-CH" content="dpr, width, viewport-width, rtt, downlink, ect, UA, UA-Platform, UA-Arch, UA-Model, UA-Mobile, UA-Full-Version" />
    <meta http-equiv="Accept-CH-Lifetime" content="86400" />
    <meta name="referrer" content="unsafe-url" />
    <meta name="viewport" content="width=1170" />
    <title>9791165341909 - 예스24</title>
    <meta name="title" content="예스24" />
    <meta name="description" content="도서, 티켓, 음반, 굿즈, 커뮤니티까지 문화 전반을 아우르는 국내 대표 문화콘텐츠 플랫폼, 아낌없는 혜택과 총알배송을 경험해보세요." />
    <meta name="keywords" content="인터넷 서점, 온라인 쇼핑, 상품 추천, 쇼핑몰, 상품 검색, 도서 정보, 국내도서, 외국도서, 전자책, eBook, 이북, 크레마, 공연, 콘서트, 뮤지컬, 음반, 예매, DVD, 블루레이, 예스24, YES24, 교보문고, 알라딘, 리센스, 예스24 도서용품, 친환경 PB 브랜드, 사은품, 굿즈" />
                                            <link title="YES24" rel="search" type="application/opensearchdescription+xml" href="//www.yes24.com/OpensearchDescription.xml">






<script src="https://image.yes24.com/sysimage/Contents/Scripts/m/common/xds.min.js?v=20250613"></script>
<script src="https://image.yes24.com/sysimage/Contents/Scripts/p/jquery/jquery-1.12.4.min.js"></script>
<script src="https://image.yes24.com/sysimage/Contents/Scripts/p/jquery/jquery.menu-aim.js?v=20260701"></script>
<script src="https://image.yes24.com/sysimage/Contents/Scripts/p/jquery/jquery.easing.1.3.min.js?v=20260701"></script>
<script src="https://www.yes24.com/Javascript/util.js?v=20260630"></script>
<script src="https://image.yes24.com/static/common/yes_header.js?v=20260630"></script>
<script src="https://www.yes24.com/Javascript/hiveSlide.js?v=20260630"></script>
<script src="https://image.yes24.com/static/common/jqueryExtendsPC.min.js?v=20260630"></script>
<script src="https://www.yes24.com/Javascript/recentviewgoods.js?v=20260630"></script>
<script src="https://image.yes24.com/static/common/bulletSearch.js?v=20260630"></script>
<script src="https://www.yes24.com/24/Scripts/YES24.Common-1.6.js?v=20260630"></script>
<script src="https://image.yes24.com/static/common/RedirectWebSiteList.min.js?v=20250613"></script>
<script src="https://image.yes24.com/static/common/RedirectWebSite.min.js?v=20250613"></script>
<script src="https://image.yes24.com/sysimage/Contents/Scripts/d/scl/simplebar.js?v=20260630"></script>
    <script src="https://image.yes24.com/sysimage/Contents/Scripts/p/jquery/jquery.lazyload.min.js?v=20260630"></script>
    <script src="https://image.yes24.com/sysimage/Contents/Scripts/p/ui/openinside.pack.js?v=20250613"></script>
    <link rel="stylesheet" type="text/css" href="https://image.yes24.com/sysimage/yesUI/hack/Newstyle.css?v=20260630" charset=&quot;euc-kr&quot; />
    <link rel="stylesheet" type="text/css" href="https://image.yes24.com/sysimage/yesUI/hack/renewHack.css?v=20260630" />
<link rel="stylesheet" type="text/css" href="https://image.yes24.com/sysimage/yesUI/yesCom.css?v=20260630" />
<link rel="stylesheet" type="text/css" href="https://image.yes24.com/sysimage/yesUI/layout/yesHeaderN4.css?v=20260630" />
<link rel="stylesheet" type="text/css" href="https://image.yes24.com/sysimage/yesUI/layout/yesFooterN4.css?v=20260901" />
<link rel="stylesheet" type="text/css" href="https://image.yes24.com/sysimage/yesUI/layout/wideLayout.css?v=20260630" />
<link rel="stylesheet" type="text/css" href="https://image.yes24.com/sysimage/yesUI/layout/simplebar.css?v=20260630" />
<link rel="stylesheet" type="text/css" href="https://image.yes24.com/sysimage/yesUI/yesUI.css?v=20260918" />
<!--[if IE]>
<link rel="stylesheet" type="text/css" href="https://image.yes24.com/sysimage/yesUI/hack/renewHack_ie.css?v=20250818" />
<![endif]-->
<link href="https://image.yes24.com/sysimage/renew/gnb/favicon_n.ico" type="image/x-icon" rel="shortcut icon" />
<script src="https://www.yes24.com/Javascript/Common.js?v=20260624"></script>
<script src="https://www.yes24.com/Javascript/headerSetting.js?v=20260630"></script>
<script src="https://image.yes24.com/static/logging/clickstream.min.js?v=20260630"></script>
<script>
    var YesData = new function () {
        var _HTTP_URL = "https://www.yes24.com";
        var _NOW_HTTP_URL = "https://www.yes24.com";
        var _BLOG_URL = "https://blog.yes24.com";
        var _IMG_HOST_IMG = "https://image.yes24.com";
        var _IsWelcomePage = "False";
        var _MEM_AGE = 0;
        var _PID = "";
        var _FRONT_API_URL = "https://frontapi.yes24.com";
        var _ParenerInfomagion = {};
        var _IsdevServer = "False";
        var _IsHttps = "True";

        this.HTTP_URL = function () { return _HTTP_URL; }
        this.NOW_HTTP_URL = function () { return _NOW_HTTP_URL; }
        this.BLOG_URL = function () { return _BLOG_URL; }
        this.IMG_HOST_IMG = function () { return _IMG_HOST_IMG; }
        this.IsWelcomePage = function () { return _IsWelcomePage; }
        this.MEM_AGE = function () { return _MEM_AGE; }
        this.PID = function () { return _PID; }
        this.FRONT_API_URL = function() {return _FRONT_API_URL;}
        this.ParenerInfomagion = function () { return _ParenerInfomagion; }
        this.IsdevServer = function () { return _IsdevServer; }
        this.IsHttps = function () { return _IsHttps; }
    }

    var PC_HTTPS_URL = "https://www.yes24.com";
    var bnSkyAdArray = new Array();                 //AD 스카이스크래퍼용
    var HeaderDisplay = "";
    var isMania = "N";
    var recentViewGoods = new RecentViewGoods();    //최근본 상품
    var SearchBarRenderingEnable = true;            //광고창을 계속 불러올지 여부
    var USERNO = "";
    var IS_NATIVE_APPS = false;
    var is_debug = Boolean(0);
    var scToday = new Date().getFullYear() + "-" + ('0' + (new Date().getMonth() + 1)).slice(-2) + "-" + ('0' + (new Date().getDate())).slice(-2);
    var scExpDate = "2023-07-06";   // 스크립트 참조 만료일 지정
    var IsScExpDate = scToday > scExpDate ? false : true;

    // 브레이즈 위한 설정 값
    var TUSERNO = '';
    var isUnder14 = 'False';
    var IS_DOMESTICIP = true;

    function activeQuickSubmenu(row) {
        var $row = $(row),
            submenuId = $row.attr('data-submenu-id'),
            $submenu = $("#" + submenuId);
        $("#quickCate > li").removeClass("on");
        $submenu.css("display", "block");
        $row.parent().addClass("on");
        if (!quickChkWide) {
            if ((document.compatMode === "CSS1Compat") || (navigator.appName != 'Microsoft Internet Explorer')) {
                $("#quickCateWrap .quickCateLiWrap").css("overflow", "hidden");
                $("#quickCateWrap .quickCateLiWrap").stop().animate({ width: "664px" }, 200, "easeInCubic", function () {
                    if ($('#quickCateWrap').css("display") == "none") {
                        $(this).css("width", "auto");
                    }
                });
            } else {
                $("#quickCateWrap .quickCateLiWrap").css("width", "564px");
            }
            quickChkWide = true;
        }
    }
    function deactiveQuickSubmenu(row) {
        var $row = $(row),
            submenuId = $row.attr('data-submenu-id'),
            $submenu = $("#" + submenuId);
        $submenu.css("display", "none");
        $row.parent().removeClass("on");
    }
    function hideUpperBn() {
        setWcode('001_001');
        var todayDate = new Date();
        setCookie("UPPER_BN_SHOW", "OK", 1); // 오른쪽 숫자는 쿠키를 유지할 기간(day)을 설정합니다
        $("#upperBnWrap").css("display", "none");
    }
    // 검색어 입력창에 포커스 시
    function SearchBarRenderingEnableSet(enable) {
        //광고 제거
        SearchBarRenderingEnable = enable;
        $("#ulSchScopeOpt").hide();
    }
    // 검색어 입력창 광고 노출
    function fnSearchBarRendering() {
        var seardtext = $('#hdSearchBarText').val();
        var bannerLink = $("#hdSearchBarLink").val();
        $('#query').val(seardtext);
        $('#query').addClass("iptTxt iptTxtAd");
        $('#keywordAd').val(bannerLink);
    }
    //검색창 선택 시
    function showLatestSearchList() {
        SearchBarRenderingEnableSet(false);
        if (String($("input#query").val()).length == 0) {
            try {
                srchHistory.show();
            } catch (e) { }
            $("#suggestSearchList").hide();
            $("#searchKeyLayer").show();
            $("#latestSearchList").show();
        } else {
            BulletSearchRenewal.InitBulletSearch();
            showSuggestSearchList();
        }
    }
    //검색창 포커스 아웃
    function blurSearchBar() {
        var queryValue = $("#query").val();
        if (queryValue == "" || queryValue == null) {
            if (location.href.toLowerCase().indexOf('/product/search') == -1) {
                fnSearchBarRendering();
                query_init = false;
            }
        }
    }
    function hideLatestSearchList() {
        $("#searchKeyLayer").hide();
        $("#latestSearchList").hide();
    }
    //추천검색어
    function showSuggestSearchList() {
        var domainVal = String($("#qdomain").val());
        if (domainVal != '티켓' && domainVal != '블로그' && domainVal != '채널예스' && domainVal != 'STORE' && domainVal != 'UsedGoods') {
            $("#latestSearchList").hide();
            $("#searchKeyLayer").show();
            $("#suggestSearchList").show();
        } else {
            $("#suggestSearchList").hide();
            $("#searchKeyLayer").show();
            $("#latestSearchList").show();
        }
    }
    function hideSuggestSearchList() {
        $("#searchKeyLayer").hide();
        $("#suggestSearchList").hide();
    }
    function closePartnerBn(close) {
        $("#bnPartnerWing").css({ "display": "none" });
        setCookie("Yes24_PartnerWingRightArea", "OK", 1);
    }
    function setCookiePartnerWingBn() {
        var name = "PartnerWingArea";
        var value = "OK";
        var expiredays = 1;
        var todayDate = new Date();
        todayDate.setDate(todayDate.getDate() + expiredays);
        document.cookie = name + "=" + escape(value) + "; path=/; expires=" + todayDate.toGMTString() + "; domain=.yes24.com;"
        closePartnerBn();
    }
    function OAS_RICHTest() {
        try {
            if (OAS_RICH.toString().indexOf("//adgirl.yes24.com/RealMedia/ads/Creatives/default/empty.gif") <= 0) {
                if (getCookie("Yes24_PartnerWingRightArea") != "OK") {
                    /*OAS_RICH("Right");*/
                    $("#bnPartnerWing a").eq(1).addClass("lnk_bn");
                }
                else {
                    $("#bnPartnerWing").css({ "display": "none" });
                }
            } else {
                $("#bnPartnerWing").css({ "display": "none" });
            }
        } catch (e) { }
    }
    function closeWindow_HeaderPid() {
        var todayDate = new Date();
        setCookieOneDay("HeaderPid_pop2", "OK", 24 - todayDate.getHours()); // 오른쪽 숫자는 쿠키를 유지할 기간(day)을 설정합니다
        $("#divYes24SCMEvent").hide();
    }
    function closeWindow__Mania_BookClub_pop() {
        var todayDate = new Date();
        setCookieOneDay("yes24_Mania_bookclub_pop", "OK", 24 - todayDate.getHours()); // 오른쪽 숫자는 쿠키를 유지할 기간(day)을 설정합니다
        $("#divYes24BookClubEvent_Mania").hide();
    }
</script>
<script src="https://image.yes24.com/static/common/frontCommon.js?v=20260624"></script>
    <!-- 광고 스크립트 - 공통 -->
    <!-- #include virtual="/Scripts/AdScript_Header.htm"-->
    <script async src="https://cdn.onetag.co.kr/0/tcs.js?eid=skxx6fnq6ueeskxx6fnq6u"></script>



<script>
    var HTTP_URL = 'https://www.yes24.com';
    var PAYMENT_HTTP_URL = 'https://ssl.yes24.com/';
    var PAYMENT_API_URL = 'https://sslapi.yes24.com';
    var IMG_HOST_SYS = 'https://image.yes24.com';
    var YES_CART_AJAX_URL = '/Product/Content/AjaxPage/Cart/Cart'
    var SARAK_URL = 'https://sarak.yes24.com';
    var SARAK_API_URL = 'https://sarak-api.yes24.com';
    var FRONT_API_URL = 'https://frontapi.yes24.com';

    var ZIP_CD = '07237';
    var ZIP_SEQ = '001';
    var BU_MNG_NO = '1156011000100150015031131';
    var memRecentZipCd = '07237';
</script>


    <script src="https://image.yes24.com/sysimage/Contents/Scripts/m/ui/clipboard.min.js?v=20260624"></script>
    <script src="/Product/Scripts/yes24common.js?v=20260929"></script>
    <script src="/Product/Scripts/Yes24.Product.Common-1.0.js?v=20261001"></script>
        <script src="/Product/Scripts/YES24.Common-1.6.js?v=20260723"></script>
        <script src="/Product/Scripts/Goods/orderPayment-3.0.js?v=20260723"></script>
        <script src="https://image.yes24.com/static/common/notificationPopup.js?v=20260918"></script>
    <script src="https://image.yes24.com/static/logging/brazeSDK.js?v=20260928"></script>
    <script src="https://image.yes24.com/static/logging/brazeHelper.js?v=20260928" defer></script>
    <script src="https://image.yes24.com/static/logging/airbridgeSDK.js?v=20260928"></script>
    <script src="https://image.yes24.com/static/logging/airbridgeHelper.js?v=20260928"></script>
    <script src="https://image.yes24.com/static/common/addon.js?v=20260204" charset="UTF-8"></script>

        <!-- Google Tag Manager -->
        <script>
            (function (w, d, s, l, i) {
                w[l] = w[l] || []; w[l].push({
                    'gtm.start':
                        new Date().getTime(), event: 'gtm.js'
                }); var f = d.getElementsByTagName(s)[0],
                    j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : ''; j.async = true; j.src =
                        'https://www.googletagmanager.com/gtm.js?id=' + i + dl; f.parentNode.insertBefore(j, f);
            })(window, document, 'script', 'dataLayer', 'GTM-WM4K93V');
        </script>
        <!-- End Google Tag Manager -->


    <link rel='stylesheet' type='text/css' media='all' href='https://image.yes24.com/sysimage/yesUI/layout/pcBase.css?v=20260922'>
    <link rel='stylesheet' type='text/css' media='all' href='https://image.yes24.com/sysimage/yesUI/search/search.css?v=20250818'>


</head>
<body>
        <!-- Google Tag Manager (noscript) -->
        <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-WM4K93V" height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
        <!-- End Google Tag Manager (noscript) -->
    <dl id="yesSkip"><dt>콘텐츠 바로가기</dt><dd><a href="#wrapperContent">본문 바로가기</a></dd></dl>
    <hr />
    <div id="yesWrap" class="">

        <script>
    var _ISADULT = "";
    var url = location.href;
    var reUrl = url.toLowerCase();
    var isWelcomePage = "False";
    var IsMania = 'False';
    var regQPop = false;
    var regBpop = false;
    var showHCPop = false;
</script>

<div id="yesHeaderArea" style="">
    <!-- ########## TOPBANNER 영역 시작 ########## -->
    <section>
        <div id="upperBnWrap" style="display:none;">
            <div id="upperBnRoll">
                <div class="upperBnSet" style="display:none;">
	<div class="upperBnArea">
		<div class="upperBnSetLft" style="background-color:#c3f4ff"><a href="https://event.yes24.com/onlyApp" onClick="setWcode('001');"><img src="https://image.yes24.com/images/01_Banner/welcome/topBanner/2026/0914_topbn_480x50_L_01.png" width="480" height="50" alt="도서앱"></a></div>
		<div class="upperBnSetRgt" style="background-color:#fff391"><a href="https://event.yes24.com/yesbenefit" onClick="setWcode('001');"><img src="https://image.yes24.com/images/01_Banner/welcome/topBanner/2026/0914_topbn_480x50_R.png" width="480" height="50" alt="혜택모음"></a></div>
	</div>
</div>


            </div>
            <div class="upperClose"><a href="javascript:void(0);" onclick="hideUpperBn();"><em class="yBlind">TOP BANNER 닫기</em></a></div>
        </div>
    </section>
    <!-- ########## TOPBANNER 영역 끝 ########## -->
    <!-- ########## HEADER 영역 시작 ########## -->
    <div id="yHeader" class="">
    <h1>
        <a class="logo" href="https://www.yes24.com/main/default.aspx" onclick="setWcode('001_004');">
        <svg role="img" aria-label="YES24" type="image/svg+xml"><image src="https://image.yes24.com/sysimage/renew/gnb/logoN4.png" xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="https://image.yes24.com/sysimage/renew/gnb/logoN4.png" width="200" height="103" alt="YES24"></image></svg>
</a>

    </h1>
    <div id="yHeaderWrap">
        <!-- %%%%%%%%%% 해더 Top 영역 시작 %%%%%%%%%% -->
        <div class="yHeaderTop">
            <h2 class="yBlind">YES24 카테고리 리스트</h2>
            <ul class="cateLi" id="ulCategoryList">
            <li class="cate001 ">
                <a title="국내도서" href="https://www.yes24.com/Mall/Main/Book/001?CategoryNumber=001" onclick="setWcode('001_002_001')" >
                    <em class="txt">국내도서</em>                </a>
            </li>
            <li class="cate002 ">
                <a title="외국도서" href="https://www.yes24.com/Mall/Main/Foreign/002?CategoryNumber=002" onclick="setWcode('001_002_002')" >
                    <em class="txt">외국도서</em>                </a>
            </li>
            <li class="cate018 ">
                <a title="중고샵" href="https://www.yes24.com/Mall/Main/used/018?CategoryNumber=018" onclick="setWcode('001_002_011')" >
                    <em class="txt">중고샵</em>                </a>
            </li>
            <li class="cate017 ">
                <a title="eBook" href="https://www.yes24.com/Mall/Main/eBook/017?CategoryNumber=017" onclick="setWcode('001_002_003')" >
                    <em class="txt">eBook</em>                </a>
            </li>
            <li class="cateCrC ">
                <a title="크레마클럽" href="https://cremaclub.yes24.com/BookClub/Main" onclick="setWcode('001_002_016')" >
                    <em class="txt">크레마클럽</em>                </a>
            </li>
            <li class="cate003 ">
                <a title="CD/LP" href="https://www.yes24.com/Mall/Main/Music/003?CategoryNumber=003" onclick="setWcode('001_002_005')" >
                    <em class="txt">CD/LP</em>                </a>
            </li>
            <li class="cate004 ">
                <a title="DVD/BD" href="https://www.yes24.com/Mall/Main/Dvd/004?CategoryNumber=004" onclick="setWcode('001_002_006')" >
                    <em class="txt">DVD/BD</em>                </a>
            </li>
            <li class="cate006 ">
                <a title="문구/GIFT" href="https://www.yes24.com/Mall/Main/Gift/006?CategoryNumber=006" onclick="setWcode('001_002_009')" >
                    <em class="txt"><u>문구</u>/GIFT</em>                </a>
<span class="gSticker"><a href="https://event.yes24.com/diaryShop">2027 다이어리</a></span>            </li>
            <li class="cateENT ">
                <a title="티켓" href="https://ticket.yes24.com" onclick="setWcode('001_002_008')" target="_blank">
                    <em class="txt">티켓</em><em class="ico_newW bgGNB">새창이동</em>                </a>
            </li>
</ul>

            <h2 class="yBlind">YES24 유틸메뉴</h2>
            <ul class="utilLi">
                <li id="LoginText">
                    <input type="hidden" id="hdfLoginYn" value="N" />
                        <a href="https://www.yes24.com/Templates/FTLogin.aspx"><em class="txt">로그인</em></a>
                </li>
                    <li><a href="https://www.yes24.com/Member/Join/Accept.aspx">회원가입</a></li>
                <li class="myPgGrp">
                    <a href="javascript:void(0);"><em class="txt">마이페이지</em><em class="ico_arrD bgGNB">하위메뉴보기</em></a>
                    <dl class="myPgDl">
                        <dt><a href="https://www.yes24.com/Member/FTMypageMain.aspx"><em class="txt">마이페이지</em><em class="ico_arrU bgGNB">이동</em></a></dt>
                        <dd>
                            <ul>
                                <li><a href="https://ssl.yes24.com/MyPageOrderList/MyPageOrderList">주문내역	 </a></li>
                                <li><a href="https://www.yes24.com/Member/FTGoMyBlog.aspx?type=list" target="_blank">마이리스트   </a></li>

In [81]:
# 뷰티풀수프(BeautifulSoup)를 이용하여 링크 찾기
from bs4 import BeautifulSoup

# 클래스 객체 생성. 첫번째 매개변수는 파싱할 HTML 문서이고, 두 번째 매개변수는 파싱에 사용할 파서
"""
파싱(parsing) : 데에터를 분석해서 의미 있는 구조로 해석하는 과정
파서(parser) : 파싱을 수행하는 소프트웨어 라이브러리

JSON패키지, XML패키지가 각각 JSON과 XML을 위한 파서
"""
soup = BeautifulSoup(r.text, 'html.parser')

In [82]:
# tag 위치 찾기 : find()
# 첫 번재 매개변수는 찾을 tag name, attrs 매개변수에는 찾으려는 tag의 속성을 dictionary로 지정
prd_link = soup.find('a', attrs={'class':'gd_name'})
print(prd_link)

<a class="gd_name" href="/product/goods/91065309" onclick="wiseLogV2('S', '101_005_003_001', ''); setGoodsClickExtraCodeHub('032', '9791165341909', '91065309', '0',this);">달러구트 꿈 백화점 1</a>

In [83]:
# 도서 링크 주소인 href 속성값 가져오기
print(prd_link['href'])

/product/goods/91065309

In [84]:
# 도서 상세 페이지 HTML 가져오기
url = "http://www.yes24.com"+prd_link["href"]
r = requests.get(url)

print(r.text)

<!DOCTYPE html>
<html lang="ko">
<head>
        <link rel="canonical" href="https://www.yes24.com/product/goods/91065309">
            <link rel="alternate" media="only screen and (max-width: 640px)" href="https://m.yes24.com/goods/detail/91065309">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge" />
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
    <meta http-equiv="Accept-CH" content="dpr, width, viewport-width, rtt, downlink, ect, UA, UA-Platform, UA-Arch, UA-Model, UA-Mobile, UA-Full-Version" />
    <meta http-equiv="Accept-CH-Lifetime" content="86400" />
    <meta name="referrer" content="unsafe-url" />
    <meta name="viewport" content="width=1170" />
    <title>달러구트 꿈 백화점 1 | 이미예 | 팩토리나인 - 예스24</title>
    <meta name="title" content="달러구트 꿈 백화점 1" />
        <meta name="author" content="이미예 저" />
    <meta name="description" content="달러구트 꿈 백화점 1. 여기는 잠들어야만 입장할 수 있는 ‘달러구트 꿈 백화점’입니다잠들어야만 입장할 수 있는 독특한 마을. 그곳에 들어온 잠든 손님들에게 가장 인기 있는 곳은, 온갖 꿈을 한데 모아 판매하는 ‘달러구트의 꿈 백화점’이다. 긴 잠을 자는 사람..." />
    <meta name="keywords" content="크레마클럽에있어요,스트레이키즈리노가읽은책,내별의책장_스트레이키즈,독서지도안,내맘대로올해의책,책읽아웃,EBS북카페,북클러버의선택,다시보는2020,올해의책,감동,청년패스,힐링판타지,주문하신 꿈은 매진입니다, DallerGut Dream Department Store: The Dream You Ordered is Sold Out, 팩토리나인,1165341905,9791165341909" />
        <meta property="og:title" content="달러구트 꿈 백화점 1 | 이미예 | 팩토리나인 - 예스24" />
            <meta property="og:type" content="book" />
            <meta property="og:url" content="https://www.yes24.com/product/goods/91065309" />
            <meta property="og:image" content="https://image.yes24.com/goods/91065309/xl" />
                    <meta property="og:site_name" content="예스24" />
            <meta property="og:description" content="여기는 잠들어야만 입장할 수 있는 ‘달러구트 꿈 백화점’입니다잠들어야만 입장할 수 있는 독특한 마을. 그곳에 들어온 잠든 손님들에게 가장 인기 있는 곳은, 온갖 꿈을 한데 모아 판매하는 ‘달러구트의 꿈 백화점’이다. 긴 잠을 자는 사람들은 물론이고, 짧은 낮잠..." />
            <meta name="twitter:card" content="summary" />
        <meta name="twitter:site" content="https://www.yes24.com/product/goods/91065309" />
        <meta name="twitter:title" content="달러구트 꿈 백화점 1 | 이미예 | 팩토리나인 - 예스24" />
        <meta name="twitter:description" content="여기는 잠들어야만 입장할 수 있는 ‘달러구트 꿈 백화점’입니다잠들어야만 입장할 수 있는 독특한 마을. 그곳에 들어온 잠든 손님들에게 가장 인기 있는 곳은, 온갖 꿈을 한데 모아 판매하는 ‘달러구트의 꿈 백화점’이다. 긴 잠을 자는 사람들은 물론이고, 짧은 낮잠..." />
        <meta name="twitter:image" content="https://image.yes24.com/goods/91065309/xl" />
        <meta property="books:isbn" content="9791165341909" />
        <meta property="books:rating:value" content="9.3" />
        <meta property="books:rating:scale" content="10" />
        <meta property="books:rating:normalized_value" content="0" />
            <link title="YES24" rel="search" type="application/opensearchdescription+xml" href="//www.yes24.com/OpensearchDescription.xml">






<script src="https://image.yes24.com/sysimage/Contents/Scripts/m/common/xds.min.js?v=20250613"></script>
<script src="https://image.yes24.com/sysimage/Contents/Scripts/p/jquery/jquery-1.12.4.min.js"></script>
<script src="https://image.yes24.com/sysimage/Contents/Scripts/p/jquery/jquery.menu-aim.js?v=20260701"></script>
<script src="https://image.yes24.com/sysimage/Contents/Scripts/p/jquery/jquery.easing.1.3.min.js?v=20260701"></script>
<script src="https://www.yes24.com/Javascript/util.js?v=20260630"></script>
<script src="https://image.yes24.com/static/common/yes_header.js?v=20260630"></script>
<script src="https://www.yes24.com/Javascript/hiveSlide.js?v=20260630"></script>
<script src="https://image.yes24.com/static/common/jqueryExtendsPC.min.js?v=20260630"></script>
<script src="https://www.yes24.com/Javascript/recentviewgoods.js?v=20260630"></script>
<script src="https://image.yes24.com/static/common/bulletSearch.js?v=20260630"></script>
<script src="https://www.yes24.com/24/Scripts/YES24.Common-1.6.js?v=20260630"></script>
<script src="https://image.yes24.com/static/common/RedirectWebSiteList.min.js?v=20250613"></script>
<script src="https://image.yes24.com/static/common/RedirectWebSite.min.js?v=20250613"></script>
<script src="https://image.yes24.com/sysimage/Contents/Scripts/d/scl/simplebar.js?v=20260630"></script>
    <script src="https://image.yes24.com/sysimage/Contents/Scripts/p/jquery/jquery.lazyload.min.js?v=20260630"></script>
    <script src="https://image.yes24.com/sysimage/Contents/Scripts/p/ui/openinside.pack.js?v=20250613"></script>
    <link rel="stylesheet" type="text/css" href="https://image.yes24.com/sysimage/yesUI/hack/Newstyle.css?v=20260630" charset=&quot;euc-kr&quot; />
    <link rel="stylesheet" type="text/css" href="https://image.yes24.com/sysimage/yesUI/hack/renewHack.css?v=20260630" />
<link rel="stylesheet" type="text/css" href="https://image.yes24.com/sysimage/yesUI/yesCom.css?v=20260630" />
<link rel="stylesheet" type="text/css" href="https://image.yes24.com/sysimage/yesUI/layout/yesHeaderN4.css?v=20260630" />
<link rel="stylesheet" type="text/css" href="https://image.yes24.com/sysimage/yesUI/layout/yesFooterN4.css?v=20260901" />
<link rel="stylesheet" type="text/css" href="https://image.yes24.com/sysimage/yesUI/layout/wideLayout.css?v=20260630" />
<link rel="stylesheet" type="text/css" href="https://image.yes24.com/sysimage/yesUI/layout/simplebar.css?v=20260630" />
<link rel="stylesheet" type="text/css" href="https://image.yes24.com/sysimage/yesUI/yesUI.css?v=20260918" />
<!--[if IE]>
<link rel="stylesheet" type="text/css" href="https://image.yes24.com/sysimage/yesUI/hack/renewHack_ie.css?v=20250818" />
<![endif]-->
<link href="https://image.yes24.com/sysimage/renew/gnb/favicon_n.ico" type="image/x-icon" rel="shortcut icon" />
<script src="https://www.yes24.com/Javascript/Common.js?v=20260624"></script>
<script src="https://www.yes24.com/Javascript/headerSetting.js?v=20260630"></script>
<script src="https://image.yes24.com/static/logging/clickstream.min.js?v=20260630"></script>
<script>
    var YesData = new function () {
        var _HTTP_URL = "https://www.yes24.com";
        var _NOW_HTTP_URL = "https://www.yes24.com";
        var _BLOG_URL = "https://blog.yes24.com";
        var _IMG_HOST_IMG = "https://image.yes24.com";
        var _IsWelcomePage = "False";
        var _MEM_AGE = 0;
        var _PID = "";
        var _FRONT_API_URL = "https://frontapi.yes24.com";
        var _ParenerInfomagion = {};
        var _IsdevServer = "False";
        var _IsHttps = "True";

        this.HTTP_URL = function () { return _HTTP_URL; }
        this.NOW_HTTP_URL = function () { return _NOW_HTTP_URL; }
        this.BLOG_URL = function () { return _BLOG_URL; }
        this.IMG_HOST_IMG = function () { return _IMG_HOST_IMG; }
        this.IsWelcomePage = function () { return _IsWelcomePage; }
        this.MEM_AGE = function () { return _MEM_AGE; }
        this.PID = function () { return _PID; }
        this.FRONT_API_URL = function() {return _FRONT_API_URL;}
        this.ParenerInfomagion = function () { return _ParenerInfomagion; }
        this.IsdevServer = function () { return _IsdevServer; }
        this.IsHttps = function () { return _IsHttps; }
    }

    var PC_HTTPS_URL = "https://www.yes24.com";
    var bnSkyAdArray = new Array();                 //AD 스카이스크래퍼용
    var HeaderDisplay = "";
    var isMania = "N";
    var recentViewGoods = new RecentViewGoods();    //최근본 상품
    var SearchBarRenderingEnable = true;            //광고창을 계속 불러올지 여부
    var USERNO = "";
    var IS_NATIVE_APPS = false;
    var is_debug = Boolean(0);
    var scToday = new Date().getFullYear() + "-" + ('0' + (new Date().getMonth() + 1)).slice(-2) + "-" + ('0' + (new Date().getDate())).slice(-2);
    var scExpDate = "2023-07-06";   // 스크립트 참조 만료일 지정
    var IsScExpDate = scToday > scExpDate ? false : true;

    // 브레이즈 위한 설정 값
    var TUSERNO = '';
    var isUnder14 = 'False';
    var IS_DOMESTICIP = true;

    function activeQuickSubmenu(row) {
        var $row = $(row),
            submenuId = $row.attr('data-submenu-id'),
            $submenu = $("#" + submenuId);
        $("#quickCate > li").removeClass("on");
        $submenu.css("display", "block");
        $row.parent().addClass("on");
        if (!quickChkWide) {
            if ((document.compatMode === "CSS1Compat") || (navigator.appName != 'Microsoft Internet Explorer')) {
                $("#quickCateWrap .quickCateLiWrap").css("overflow", "hidden");
                $("#quickCateWrap .quickCateLiWrap").stop().animate({ width: "664px" }, 200, "easeInCubic", function () {
                    if ($('#quickCateWrap').css("display") == "none") {
                        $(this).css("width", "auto");
                    }
                });
            } else {
                $("#quickCateWrap .quickCateLiWrap").css("width", "564px");
            }
            quickChkWide = true;
        }
    }
    function deactiveQuickSubmenu(row) {
        var $row = $(row),
            submenuId = $row.attr('data-submenu-id'),
            $submenu = $("#" + submenuId);
        $submenu.css("display", "none");
        $row.parent().removeClass("on");
    }
    function hideUpperBn() {
        setWcode('001_001');
        var todayDate = new Date();
        setCookie("UPPER_BN_SHOW", "OK", 1); // 오른쪽 숫자는 쿠키를 유지할 기간(day)을 설정합니다
        $("#upperBnWrap").css("display", "none");
    }
    // 검색어 입력창에 포커스 시
    function SearchBarRenderingEnableSet(enable) {
        //광고 제거
        SearchBarRenderingEnable = enable;
        $("#ulSchScopeOpt").hide();
    }
    // 검색어 입력창 광고 노출
    function fnSearchBarRendering() {
        var seardtext = $('#hdSearchBarText').val();
        var bannerLink = $("#hdSearchBarLink").val();
        $('#query').val(seardtext);
        $('#query').addClass("iptTxt iptTxtAd");
        $('#keywordAd').val(bannerLink);
    }
    //검색창 선택 시
    function showLatestSearchList() {
        SearchBarRenderingEnableSet(false);
        if (String($("input#query").val()).length == 0) {
            try {
                srchHistory.show();
            } catch (e) { }
            $("#suggestSearchList").hide();
            $("#searchKeyLayer").show();
            $("#latestSearchList").show();
        } else {
            BulletSearchRenewal.InitBulletSearch();
            showSuggestSearchList();
        }
    }
    //검색창 포커스 아웃
    function blurSearchBar() {
        var queryValue = $("#query").val();
        if (queryValue == "" || queryValue == null) {
            if (location.href.toLowerCase().indexOf('/product/search') == -1) {
                fnSearchBarRendering();
                query_init = false;
            }
        }
    }
    function hideLatestSearchList() {
        $("#searchKeyLayer").hide();
        $("#latestSearchList").hide();
    }
    //추천검색어
    function showSuggestSearchList() {
        var domainVal = String($("#qdomain").val());
        if (domainVal != '티켓' && domainVal != '블로그' && domainVal != '채널예스' && domainVal != 'STORE' && domainVal != 'UsedGoods') {
            $("#latestSearchList").hide();
            $("#searchKeyLayer").show();
            $("#suggestSearchList").show();
        } else {
            $("#suggestSearchList").hide();
            $("#searchKeyLayer").show();
            $("#latestSearchList").show();
        }
    }
    function hideSuggestSearchList() {
        $("#searchKeyLayer").hide();
        $("#suggestSearchList").hide();
    }
    function closePartnerBn(close) {
        $("#bnPartnerWing").css({ "display": "none" });
        setCookie("Yes24_PartnerWingRightArea", "OK", 1);
    }
    function setCookiePartnerWingBn() {
        var name = "PartnerWingArea";
        var value = "OK";
        var expiredays = 1;
        var todayDate = new Date();
        todayDate.setDate(todayDate.getDate() + expiredays);
        document.cookie = name + "=" + escape(value) + "; path=/; expires=" + todayDate.toGMTString() + "; domain=.yes24.com;"
        closePartnerBn();
    }
    function OAS_RICHTest() {
        try {
            if (OAS_RICH.toString().indexOf("//adgirl.yes24.com/RealMedia/ads/Creatives/default/empty.gif") <= 0) {
                if (getCookie("Yes24_PartnerWingRightArea") != "OK") {
                    /*OAS_RICH("Right");*/
                    $("#bnPartnerWing a").eq(1).addClass("lnk_bn");
                }
                else {
                    $("#bnPartnerWing").css({ "display": "none" });
                }
            } else {
                $("#bnPartnerWing").css({ "display": "none" });
            }
        } catch (e) { }
    }
    function closeWindow_HeaderPid() {
        var todayDate = new Date();
        setCookieOneDay("HeaderPid_pop2", "OK", 24 - todayDate.getHours()); // 오른쪽 숫자는 쿠키를 유지할 기간(day)을 설정합니다
        $("#divYes24SCMEvent").hide();
    }
    function closeWindow__Mania_BookClub_pop() {
        var todayDate = new Date();
        setCookieOneDay("yes24_Mania_bookclub_pop", "OK", 24 - todayDate.getHours()); // 오른쪽 숫자는 쿠키를 유지할 기간(day)을 설정합니다
        $("#divYes24BookClubEvent_Mania").hide();
    }
</script>
<script src="https://image.yes24.com/static/common/frontCommon.js?v=20260624"></script>
    <!-- 광고 스크립트 - 공통 -->
    <!-- #include virtual="/Scripts/AdScript_Header.htm"-->
    <script async src="https://cdn.onetag.co.kr/0/tcs.js?eid=skxx6fnq6ueeskxx6fnq6u"></script>



<script>
    var HTTP_URL = 'https://www.yes24.com';
    var PAYMENT_HTTP_URL = 'https://ssl.yes24.com/';
    var PAYMENT_API_URL = 'https://sslapi.yes24.com';
    var IMG_HOST_SYS = 'https://image.yes24.com';
    var YES_CART_AJAX_URL = '/Product/Content/AjaxPage/Cart/Cart'
    var SARAK_URL = 'https://sarak.yes24.com';
    var SARAK_API_URL = 'https://sarak-api.yes24.com';
    var FRONT_API_URL = 'https://frontapi.yes24.com';

    var ZIP_CD = '07237';
    var ZIP_SEQ = '001';
    var BU_MNG_NO = '1156011000100150015031131';
    var memRecentZipCd = '07237';
</script>


    <script src="https://image.yes24.com/sysimage/Contents/Scripts/m/ui/clipboard.min.js?v=20260624"></script>
    <script src="/Product/Scripts/yes24common.js?v=20260929"></script>
    <script src="/Product/Scripts/Yes24.Product.Common-1.0.js?v=20261001"></script>
        <script src="/Product/Scripts/YES24.Common-1.6.js?v=20260723"></script>
        <script src="/Product/Scripts/Goods/orderPayment-3.0.js?v=20260723"></script>
        <script src="https://image.yes24.com/static/common/notificationPopup.js?v=20260918"></script>
    <script src="https://image.yes24.com/static/logging/brazeSDK.js?v=20260928"></script>
    <script src="https://image.yes24.com/static/logging/brazeHelper.js?v=20260928" defer></script>
    <script src="https://image.yes24.com/static/logging/airbridgeSDK.js?v=20260928"></script>
    <script src="https://image.yes24.com/static/logging/airbridgeHelper.js?v=20260928"></script>
    <script src="https://image.yes24.com/static/common/addon.js?v=20260204" charset="UTF-8"></script>




        <!-- Google Tag Manager -->
        <script>
            (function (w, d, s, l, i) {
                w[l] = w[l] || []; w[l].push({
                    'gtm.start':
                        new Date().getTime(), event: 'gtm.js'
                }); var f = d.getElementsByTagName(s)[0],
                    j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : ''; j.async = true; j.src =
                        'https://www.googletagmanager.com/gtm.js?id=' + i + dl; f.parentNode.insertBefore(j, f);
            })(window, document, 'script', 'dataLayer', 'GTM-WM4K93V');
        </script>
        <!-- End Google Tag Manager -->


    <link rel='stylesheet' type='text/css' media='all' href='https://image.yes24.com/sysimage/YESUI/detail/detail_2nd.css?v=20260602'>
    <link rel='stylesheet' type='text/css' media='all' href='https://image.yes24.com/sysimage/YESUI/detail/detail_class.css?v=20260602'>
    <link rel='stylesheet' type='text/css' media='all' href='https://image.yes24.com/sysimage/yesUI/yesLocation.css?v=20250818'>





<!-- 구조화된 데이터 -->
<script type="application/ld+json">
    {
        "@context": "https://schema.org",
        "@type": ["Book","Product"],
        "name": "달러구트 꿈 백화점 1",
        "image": {
            "@type": "ImageObject",
            "url": "https://image.yes24.com/goods/91065309/xl",
            "contentUrl": "https://image.yes24.com/goods/91065309/xl",
            "name": "달러구트 꿈 백화점 1",
            "creditText": "YES24 제공"
        },
        "description": "달러구트 꿈 백화점 1, 여기는 잠들어야만 입장할 수 있는 ‘달러구트 꿈 백화점’입니다잠들어야만 입장할 수 있는 독특한 마을. 그곳에 들어온 잠든 손님들에게 가장 인기 있는 곳은, 온갖 꿈을 한데 모아 판매하는 ‘달러구트의 꿈 백화점’이다. 긴 잠을 자는 사람...",
        "genre": ["소설/시/희곡","장르소설","판타지"],
        "keywords": "달러구트꿈백화점1, 크레마클럽에있어요, 스트레이키즈리노가읽은책, 내별의책장_스트레이키즈, 독서지도안, 내맘대로올해의책, 책읽아웃, EBS북카페, 북클러버의선택, 다시보는2020, 올해의책, 감동, 청년패스, 힐링판타지, 주문하신 꿈은 매진입니다, DallerG...",
        "isbn": "9791165341909",
        "sku": "91065309",
        "bookFormat": "https://schema.org/Paperback",
        "datePublished": "2020-07-08",
        "numberOfPages": 300,
            "inLanguage": "ko-KR",
        "url": "https://www.yes24.com/product/goods/91065309",
    "aggregateRating": {
          "@type": "AggregateRating",
          "ratingValue": 9.3,
          "reviewCount": 4602,
          "bestRating": 10.0,
          "worstRating": 0.0
        },
    "author": {"@type":"Person","@id":"https://www.yes24.com/product/author/305800","url":"https://www.yes24.com/product/author/305800","name":"이미예"},"creditText": "이미예 저",        "publisher": {
            "@type":"Organization",
            "name":"팩토리나인"
        },

        "isPartOf": {
            "@type": "BookSeries",
            "name": "달러구트 꿈 백화점",
            "url": "https://www.yes24.com//product/category/series/001?SeriesNumber=292554"
        },

        "offers": {
            "@type": "Offer",
            "price": 16020,
            "priceCurrency": "KRW",
            "availability": "https://schema.org/InStock",
            "url": "https://www.yes24.com/product/goods/91065309",
            "itemCondition": "https://schema.org/NewCondition",
            "seller": {
                "@type": "Organization",
                "name": "YES24"
            }

        },
        "workExample": [{
            "@type": "Book",
            "name": "달러구트 꿈 백화점 : 잠들어야만 입장 가능합니다",
            "bookFormat": "https://schema.org/EBook",
            "isbn": "9791165341053",
            "inLanguage": "ko-KR",
            "url": "https://www.yes24.com/product/goods/90051766"
            }]


    }
</script>

</head>
<body>
        <!-- Google Tag Manager (noscript) -->
        <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-WM4K93V" height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
        <!-- End Google Tag Manager (noscript) -->
    <dl id="yesSkip"><dt>콘텐츠 바로가기</dt><dd><a href="#wrapperContent">본문 바로가기</a></dd></dl>
    <hr />
    <div id="yesWrap" class="">

        <script>
    var _ISADULT = "";
    var url = location.href;
    var reUrl = url.toLowerCase();
    var isWelcomePage = "False";
    var IsMania = 'False';
    var regQPop = false;
    var regBpop = false;
    var showHCPop = false;
</script>

<div id="yesHeaderArea" style="">
    <!-- ########## TOPBANNER 영역 시작 ########## -->
    <section>
        <div id="upperBnWrap" style="display:none;">
            <div id="upperBnRoll">
                <div class="upperBnSet" style="display:none;">
	<div class="upperBnArea">
		<div class="upperBnSetLft" style="background-color:#c3f4ff"><a href="https://event.yes24.com/onlyApp" onClick="setWcode('001');"><img src="https://image.yes24.com/images/01_Banner/welcome/topBanner/2026/0914_topbn_480x50_L_01.png" width="480" height="50" alt="도서앱"></a></div>
		<div class="upperBnSetRgt" style="background-color:#fff391"><a href="https://event.yes24.com/yesbenefit" onClick="setWcode('001');"><img src="https://image.yes24.com/images/01_Banner/welcome/topBanner/2026/0914_topbn_480x50_R.png" width="480" height="50" alt="혜택모음"></a></div>
	</div>
</div>


            </div>

In [85]:
# 뷰티플수프 객체를 새로 생성하고 find() method로 품목정보를 찾아서 출력
soup = BeautifulSoup(r.text, 'html.parser')
prd_detail = soup.find('div', attrs={'id':'infoset_specific'})
print(prd_detail)

<div class="gd_infoSet infoSet_noLine" id="infoset_specific">
<div class="tm_infoSet">
<h4 class="tit_txt">품목정보</h4>
</div>
<div class="infoSetCont_wrap">
<div class="yesTb">
<table class="tb_nor tb_vertical" summary="품목정보 국내도서, 외국도서 " width="100%">
<caption>품목정보</caption>
<colgroup>
<col width="170"/>
<col width="*"/>
</colgroup>
<tbody class="b_size">
<tr>
<th class="txt" scope="row">발행일</th>
<td class="txt lastCol">2020년 07월 08일</td>
</tr>
<tr>
<th class="txt" scope="row">쪽수, 무게, 크기</th>
<td class="txt lastCol">300쪽 | 362g | 134*200*20mm</td>
</tr>
<tr>
<th class="txt" scope="row">ISBN13</th>
<td class="txt lastCol">9791165341909</td>
</tr>
<tr>
<th class="txt" scope="row">ISBN10</th>
<td class="txt lastCol">1165341905</td>
</tr>
</tbody>
</table>
</div>
</div>
<script type="text/javascript">
        if ($("#infoset_specific table tbody tr").length == 0) {
            $("#infoset_specific").remove();
        }
    </script>
</div>

div tag 대신 table tag로 도서 쪽수를 찾아도 되지만 table tag가 모든 도서 상세 페이지에서 유일하다고 장담할 수 없기 때문에 최대한 유일한 tag의 class를 가져와야 한다.

In [86]:
# table tag를 list로 가져오기 : find_all()
prd_tr_list = prd_detail.find_all('tr')
print(prd_tr_list)

[<tr>
<th class="txt" scope="row">발행일</th>
<td class="txt lastCol">2020년 07월 08일</td>
</tr>, <tr>
<th class="txt" scope="row">쪽수, 무게, 크기</th>
<td class="txt lastCol">300쪽 | 362g | 134*200*20mm</td>
</tr>, <tr>
<th class="txt" scope="row">ISBN13</th>
<td class="txt lastCol">9791165341909</td>
</tr>, <tr>
<th class="txt" scope="row">ISBN10</th>
<td class="txt lastCol">1165341905</td>
</tr>]

In [87]:
# tag안의 text 가져오기 : get_text()
for tr in prd_tr_list :
    if tr.find('th').get_text() == "쪽수, 무게, 크기" :
        page_td = tr.find('td').get_text()
        break

print(page_td)

300쪽 | 362g | 134*200*20mm

In [88]:
# python 문자열 객체에서 도서 쪽수만 가져오기
print(page_td.split()[0])

300쪽

판다스 데이터프레임은 한 행씩 순차적으로 처리하는데 최적화되어 있지 않음 -> for문으로 반복하는 것은 매우 비효율적
대신 데이터프레임은 각 행 또는 각 열에 원하는 함수를 자동으로 적용해 주는 여러 가지 방법을 제공

1. 온라인 서점 검색 페이지 URL 생성
2. `requests.get()` method로 검색 결과 페이지의 HTML 가져오기
3. `BeautifulSoup`로 HTML 파싱
4. `BeautifulSoup` `find()` method로 상세 페이지 URL 추출
5. `requests.get()` method로 도서 상세 페이지의 HTML 가져오기
6. `BeautifulSoup`로 HTML 파싱
7. `BeautifulSoup` `find()` method로 품목정보 tag 찾기
8. `BeautifulSoup` `find_all()` method로 쪽수가 들어있는 tag 찾기
9. 앞에서 찾은 테이블의 행에서 `get_text()` method로 해당 tag에 들어있는 쪽수 가져오기

이 작업을 수행하는 함수를 생성 (ISBN 정수 값을 받아 쪽수를 반환)

In [89]:
def get_page_cnt(isbn:int) :
    # yes24 도서 검색 페이지 URL
    url = 'http://www.yes24.com/Product/Search?domain=BOOK&query={}'

    # url에 isbon을 넣어 HTML 가져오기
    r = requests.get(url.format(isbn))

    # HTML 파싱
    soup = BeautifulSoup(r.text, 'html.parser')

    # 검색 결과에서 해당 도서 선택
    prd_info = soup.find('a', attrs={'class':'gd_name'})
    if prd_info is None :
        return ''

    # 도서 상세 페이지
    url = 'http://yes24.com' + prd_info['href']
    r = requests.get(url)

    # HTML 파싱
    soup = BeautifulSoup(r.text, 'html.parser')

    # 품목정보 선택
    prd_detail = soup.find("div", attrs={'id':'infoset_specific'})

    # table에 있는 tag 가져오기
    prd_tr_list = prd_detail.find_all('tr')

    # 쪽수가 들어있는 곳을 찾아 값을 반환
    for tr in prd_tr_list :
        if tr.find('th').get_text() == "쪽수, 무게, 크기" :
            return tr.find('td').get_text().split()[0]
    return ''

# get_page_cnt() 함수가 잘 동작하는지 확인
get_page_cnt(9791165341909)

'300쪽'

각 행의 반복 작업을 수행하기 위해 데이터프레임은 apply() method제공
apply() method의 첫 번째 매개변수는 실행할 함수 -> 데이터프레임의 한 행을 받아 `get_page_cnt()`함수를 사용해 쪽수를 구하는 함수 필요
apply() method의 두 번째 매개변수는 axis : 행/열 중 어디에 적용할 것인지 결정(default는 0으로 열, 1은 행에 적용)

In [90]:
# 데이터프레임 행 혹은 열에 함수 적용하기 : apply(실행할 함수, axis)

# 10개의 책에 대해서 실행
top10_books = books.head(10)

# get_page_cnt2()는 
def get_page_cnt2(row) :
    isbn = row['isbn13']
    return get_page_cnt(isbn)

page_count = top10_books.apply(get_page_cnt2, axis=1)
print(page_count)

0    300쪽
1    264쪽
2     88쪽
3     88쪽
4     88쪽
5    168쪽
6     88쪽
7    340쪽
8    147쪽
9     88쪽
dtype: str

### 함수를 두 번 만들지 않고 간결하게 작성하는 방법 : lambda function
lambda는 익명 함수를 생성하는 키워드로 다음과 같이 구성된다.
>```python
>lambda 매개변수: 표현식
>```
* 매개변수 : 함수에 전달할 입력값
* 표현식 : 실행하고 반환할 결과

다음은 add함수를 lambda로 표현한 것이다.
>```python
># add function 정의
>def add(x, y):
>    return x+y
># add function 실행
>print(add(3, 5))  # 8
>
># add function을 lambda로 정의
>add = lambda x, y: x+y
># add function 실행
>print(add(3, 5))  # 8
>```

상단의 `get_page_cnt2`를 lambda로 표현하면 다음과 같다.

>```python
>page_cnt = top10_books.apply(lambda row: get_page_cnt(row['isbn13']), axis=1)
>```

또 다른 방법으로는 데이터프레임의 각 열에 aaply() method를 적용한ㄴ 방법이 있다.
>```python
>some_df.apply(lambda column: some_func(column), axis=0)
>```

In [91]:
# page_count 시리즈 객체에 이름 지정
page_count.name = 'page_count'
print(page_count)

0    300쪽
1    264쪽
2     88쪽
3     88쪽
4     88쪽
5    168쪽
6     88쪽
7    340쪽
8    147쪽
9     88쪽
Name: page_count, dtype: str

In [92]:
# 데이터프레임과 시리즈 합치기 : merge()
# 첫 번째와 두 번째 매개변수는 합칠 데이터프레임이나 시리즈 객체이며, 두 객체의 인덱스를 기준으로 합칠 경우 left_index, right_index 매개변수를 True로 지정

top10_with_page_count = pd.merge(top10_books, page_count, left_index=True, right_index=True)
top10_with_page_count

,no,ranking,bookname,authors,publisher,publication_year,isbn13,page_count
0,1,1,달러구트 꿈 백화점 :주문하신 꿈은 매진입니다,지은이: 이미예,팩토리나인,2020,9791165341909,300쪽
1,2,2,아몬드 :손원평 장편소설,지은이: 손원평,창비,2017,9788936434267,264쪽
2,3,3,(추리 천재) 엉덩이 탐정,트롤 글·그림 ;김정화 옮김,미래엔,2016,9791164134090,88쪽
3,4,4,(추리 천재) 엉덩이 탐정,트롤 글·그림 ;김정화 옮김,미래엔,2016,9791162339466,88쪽
4,5,5,(추리 천재) 엉덩이 탐정,트롤 글·그림 ;김정화 옮김,미래엔,2016,9791164131914,88쪽
5,6,6,흔한남매,원작: 흔한남매 ;그림: 유난희,미래엔,2019,9791164134267,168쪽
6,7,7,(추리 천재) 엉덩이 탐정,트롤 글·그림 ;김정화 옮김,미래엔,2016,9791162332542,88쪽
7,8,8,"시선으로부터, :정세랑 장편소설",지은이: 정세랑,문학동네,2020,9788954672214,340쪽
8,9,9,(이상한 과자 가게) 전천당,히로시마 레이코 글 ;김정화 옮김,길벗스쿨,2019,9791164060481,147쪽
9,10,10,(추리 천재) 엉덩이 탐정,트롤 글·그림 ;김정화 옮김,미래엔,2016,9788937848247,88쪽

# merge() 함수의 매개변수
1. `on` : 합쳐질 때 기준이 되는 열 지정
2. `how` : 합쳐질 방식 지정. 아때 없는 값들은 `NaN`으로 표시됨.
    * default=inner : 두 데이터프레임의 값이 같은 행만 합쳐짐
    * left : 첫 번째 데이터프레임을 기준으로 두 번째 데이터프레임을 합침
    * right : 두 번째 데이터프레임을 기준으로 첫 번째 데이터프레임을 합침
    * outer : 두 데이터프레임의 모든 행을 유지하면서 합침
        * 동일한 행은 합쳐지고 그렇지 않은 행은 별개의 행으로 추가됨
3. left_on, right_on : 합칠 기준이 되는 열의 이름이 서로 다를 경우 각각의 매개변수에 지정할 수 있음
4. left_index, right_index : 합칠 기준이 열이 아니라 index일 경우 boolean값으로 지정
    * 두 데이터프레임에 동일한 이름의 열이 존재할 경우 첫 번째 데이터프레임의 열 이름에는 `_x` 접미사가 붙고, 두 번째 데이터프레임의 열 이름에는 `_y`접미사가 붙음

In [105]:
import json
from io import StringIO
import pandas as pd

df1_str = """
[
    {"col1":"a", "col2":1},
    {"col1":"b", "col2":2},
    {"col1":"c", "col2":3}
]
"""
# 데이터프레임 df1 생성
df1 = pd.DataFrame(json.loads(df1_str))
pd.read_json(StringIO(df1_str))

  col1  col2
0    a     1
1    b     2
2    c     3

In [106]:
df2_str = """
[
    {"col1":"a", "col3":10},
    {"col1":"b", "col3":20},
    {"col1":"d", "col3":30}
]
"""
# 
# 데이터프레임 df2 생성
df2 = pd.DataFrame(json.loads(df2_str))
pd.read_json(StringIO(df2_str))

  col1  col3
0    a    10
1    b    20
2    d    30

In [107]:
# on 매개변수
pd.merge(df1, df2, on="col1")

  col1  col2  col3
0    a     1    10
1    b     2    20

In [108]:
# how 매개변수 - left
pd.merge(df1, df2, how='left', on='col1')

  col1  col2  col3
0    a     1  10.0
1    b     2  20.0
2    c     3   NaN

In [109]:
# how 매개변수 - right
pd.merge(df1, df2, how='right', on='col1')

  col1  col2  col3
0    a   1.0    10
1    b   2.0    20
2    d   NaN    30

In [110]:
# how 매개변수 - outer
pd.merge(df1, df2, how='outer', on='col1')

  col1  col2  col3
0    a   1.0  10.0
1    b   2.0  20.0
2    c   3.0   NaN
3    d   NaN  30.0

In [111]:
# left_on, right_on
pd.merge(df1, df2, left_on="col1", right_on="col1")

  col1  col2  col3
0    a     1    10
1    b     2    20

In [112]:
# left_index, right_index
pd.merge(df1, df2, left_on="col2", right_index=True)

  col1_x  col2 col1_y  col3
0      a     1      b    20
1      b     2      d    30