# 데이터 분석이란
* 데이터 분석
    * 데이터를 수집, 처리, 정제, 분석, 모델링하여 의사 결정을 내리는 데 도움을 주는 작업
    * 통계학과 머신러닝의 기술을 사용하고 비즈니스 문제를 해결하기 위해 도메인 지식이 필요
* 데이터 고학
    * 데이터 분석, 머신러닝을 아우르는 개념
    * 데이터 분석에 비해 머신러닝 모델을 만들어 문제를 해결하는데 많은 비중을 둠
* 파이썬
    * 데이터 분석, 데이터 과학, 머신러닝 작업에 사용할 수 있는 인기 있는 프로그래밍 언어
    * 넘파이, 판다스, 맷플롯립 등 데이터 분석에 필요한 다양한 패키지를 손쉽게 사용할 수있음

# 데이터 분석에 사용되는 핵심 패키지
1. 넘파이(numpy)
    * 과학 계산과 배열에 필요한 수학 패키지
2. 판다스(pandas)
    * 숫자와 문자를 섞어 표처럼 사용할 수 있는 데이터프레임 제공
3. 맷플롯립(matplotlib)
    * 동적, 정적 그래프를 만들 수 있는 시각화 패키지
4. 사이파이(scipy)
    * 수학과 과학 계산 전문 패키지로 미적분, 선형 대수 등을 포함
5. 사이킷런(scikit-learn)
    * 파이썬에서 사용할 수 있는 대표적인 머신러닝 패키지

In [1]:
import gdown  # 구글 드라이브를 포함하여 웹에서 대용량 파일을 다운로드할 수 있는 pkg

gdown.download('http://bit.ly/3eecMKZ', '남산도서관 장서 대출목록 (2021년 04월).csv', quiet=False)

Downloading...
From: http://bit.ly/3eecMKZ
To: c:\김태경\공부\TIL\데이터분석\01\남산도서관 장서 대출목록 (2021년 04월).csv
100%|██████████| 58.1M/58.1M [00:01<00:00, 41.1MB/s]

'남산도서관 장서 대출목록 (2021년 04월).csv'

In [2]:
# csv파일은 text파일이므로 python의 open() 함수로 읽을 수 있음 -> with문으로 파일을 열 수 있음
with open("남산도서관 장서 대출목록 (2021년 04월).csv") as f :
    print(f.readline()) # readline은 한 줄을 읽을 수 있음
    print(f.readline())

번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자,

"1","인공지능과 흙","김동훈 지음","민음사","2021","9788937444319","","","","","1","0","2021-03-19",

In [ ]:
import chardet  # 문자 인코딩 방식을 알 수 있는 pkg

# open() 함수로 text 파일을 열 때 mode 매개변수를 binary 일기 모드인 'rb'로 지정. mode매개변수의 기본값은 text읽기 모드인 'r'
with open("남산도서관 장서 대출목록 (2021년 04월).csv", mode='rb') as f :
    d = f.readline()
print(chardet.detect(d))

# CP949 인코딩 방식은 EUC-KR 인코딩 방식의 확장형
# EUC-KR 형식으로 인코딩 된 파일은 CP949 형식으로 "무조건" 읽을 수 있음
# CP949 형식으로 인코딩 된 파일은 EUC-KR 형식으로 일부 문자를 읽을 수 없음 (항상 읽을 수 있는 것은 아님)

{'encoding': 'CP949', 'confidence': 0.2517948406553882, 'language': 'ko', 'mime_type': 'text/plain'}

In [ ]:
# pandas는 csv파일을 읽어 '데이터프레임'이라는 표 형식 데이터로 저장
import pandas as pd  # as를 활용하여 import한 pkg 이름을 모두 쓰지 않고 약어 등으로 바꿔서 사용할 수 있음

# read_csv : pandas에서 csv파일을 읽을 때 사용하는 함수
# encoding 매개변수 : data를 읽어올 encoding 방식
df = pd.read_csv("남산도서관 장서 대출목록 (2021년 04월).csv", encoding="EUC-KR")

"""
경고 발생!!!
pandas는 csv파일을 읽을 때 같은 열에 어떤 종류의 데이터가 저장되어 있는지 자동으로 파악함
예를 들어 '도서명'은 문자열, '대출건수'는 정수로 인식함
그러나 메모리를 효율적으로 사용하기 위해 csv파일을 조금씩 나누어 읽음
이때 자동으로 파악한 데이터 타입이 달라지면 경고 발생

해결 방법은 2가지로 존재
1. low_memory 매개변수 활용
2. dtype 매개변수 활용
"""

C:\Users\rlaxo\AppData\Local\Temp\ipykernel_14624\2526771603.py:6: DtypeWarning: Columns (5: ISBN, 6: 세트 ISBN, 9: 주제분류번호) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("남산도서관 장서 대출목록 (2021년 04월).csv", encoding="EUC-KR")

In [19]:
# low_memory 매개 변수를 False로 지정하여 파일을 나누어 읽지 않고 한 번에 읽음 -> 많은 메모리 사용
df = pd.read_csv("남산도서관 장서 대출목록 (2021년 04월).csv", encoding="EUC-KR", low_memory=False)

In [ ]:
# dtype매개변수로 열의 데이터 타입을 자동으로 찾지 않고 데이터 타입을 지정
df = pd.read_csv("남산도서관 장서 대출목록 (2021년 04월).csv", encoding="EUC-KR", dtype={'ISBN':str, '세트 ISBN':str, '주제분류번호':str})

In [ ]:
df = pd.read_csv("남산도서관 장서 대출목록 (2021년 04월).csv", encoding="EUC-KR", low_memory=False)
# head() 함수는 처음 5개 행 확인 가능
df.head()
# 이때 첫번째 열은 데이터프레임의 index

# 실행 결과 마지막 열에 원래 csv파일에 없던 'Unnamed:13'열이 생겼음
# csv파일 각 라인의 끝에 콤마(,)가 있어서 pandas는 이 콤마를 보고 마지막에 하나의 열이 더 있다고 판단헀기 때문

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자,Unnamed: 13
0,1,인공지능과 흙,김동훈 지음,민음사,2021,9788937444319,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN
1,2,가짜 행복 권하는 사회,김태형 지음,갈매나무,2021,9791190123969,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN
2,3,나도 한 문장 잘 쓰면 바랄 게 없겠네,김선영 지음,블랙피쉬,2021,9788968332982,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN
3,4,예루살렘 해변,"이도 게펜 지음, 임재희 옮김",문학세계사,2021,9788970759906,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN
4,5,김성곤의 중국한시기행 : 장강·황하 편,김성곤 지음,김영사,2021,9788934990833,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN

1. header 매개변수
    * csv 파일의 첫 행이 열에 대한 이름이 아니라면 `read_csv()`함수 호출 시 header 매개변수를 None으로 지정하여 데이터 첫 행에 열 이름이 없다는 것을 알림
2. names 매개변수
    * 열 이름 리스트를 따로 전달하는 매개변수
    * 이때 names 매개변수에 전달하는 열 이름에 중복된 이름이 있어서는 안됨

In [21]:
# to_csv : 데이터프레임을 csv파일로 저장 (기본적으로 UTF-8 형식으로 저장)
df.to_csv('ns_202104.csv')

In [ ]:
with open('no_202104.csv', encoding="UTF-8") as f :
    for i in range(3) :
        print(f.readline())

# 기존 CSV파일과 다르게 CSV파일 맨 왼쪽에 데이터프레임에 있던 행 index가 함께 저장됨

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자,Unnamed: 13

0,1,인공지능과 흙,김동훈 지음,민음사,2021,9788937444319,,,,,1,0,2021-03-19,

1,2,가짜 행복 권하는 사회,김태형 지음,갈매나무,2021,9791190123969,,,,,1,0,2021-03-19,

In [ ]:
# index까지 저장된 CSV파일을 다시 데이터프레임으로 읽는다면, index가 다시 생성되면서 'Unnamed:0'이라는 첫번째 열과 중복됨.
ns_df = pd.read_csv('ns_202104.csv', low_memory=False)
ns_df.head()

"""
index가 다시 생성되는 것을 방지하는 방법
1. index열이 있다는 것을 알려줌
2. index를 빼고 저장
"""

,Unnamed: 0,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자,Unnamed: 13
0,0,1,인공지능과 흙,김동훈 지음,민음사,2021,9788937444319,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN
1,1,2,가짜 행복 권하는 사회,김태형 지음,갈매나무,2021,9791190123969,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN
2,2,3,나도 한 문장 잘 쓰면 바랄 게 없겠네,김선영 지음,블랙피쉬,2021,9788968332982,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN
3,3,4,예루살렘 해변,"이도 게펜 지음, 임재희 옮김",문학세계사,2021,9788970759906,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN
4,4,5,김성곤의 중국한시기행 : 장강·황하 편,김성곤 지음,김영사,2021,9788934990833,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN

In [23]:
# index_col 매개변수를 사용하여 csv파일에 index가 이미 있다는 것을 알려줌
ns_df = pd.read_csv('ns_202104.csv', index_col=0, low_memory=False)
ns_df.head()

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자,Unnamed: 13
0,1,인공지능과 흙,김동훈 지음,민음사,2021,9788937444319,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN
1,2,가짜 행복 권하는 사회,김태형 지음,갈매나무,2021,9791190123969,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN
2,3,나도 한 문장 잘 쓰면 바랄 게 없겠네,김선영 지음,블랙피쉬,2021,9788968332982,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN
3,4,예루살렘 해변,"이도 게펜 지음, 임재희 옮김",문학세계사,2021,9788970759906,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN
4,5,김성곤의 중국한시기행 : 장강·황하 편,김성곤 지음,김영사,2021,9788934990833,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN

In [25]:
# index를 빼고 저장
df.to_csv('ns_202104_no_index.csv', index=False)